### ISSUE TITLE
Azure deploy stage issue?

### ISSUE THREAD

**Issue by LLLIEFA** [nightscout/cgm-remote-monitor#1533]
Any idea guys?

I tried updating an App setting in Azure and that kept failing (said to try later, so not sure if below is a cause of a problem), but I went on checking what I could fine (not very familiar with this all yet), and found my 'continuous deployment' and tried a sync...but that keeps failing at the deployment stage..

I believe I pulled from master last Saturday and merged it (using the same name of my fork) and it is working fine, just this new app setting doesn't want to take (only want to add "ENABLE" "upbat")
So not sure if I need to do anything but wait, but it looks like something is not working ok.
See below for the error:

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json object-component@0.0.3 No repository field.
npm WARN package.json parsejson@0.0.1 No repository field.
npm WARN package.json parsejson@0.0.1 No README data
npm WARN package.json parseuri@0.0.2 No repository field.
npm WARN package.json parseuri@0.0.2 No README data
npm WARN package.json parseqs@0.0.2 No repository field.
npm WARN package.json parseqs@0.0.2 No README data
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json has-binary@0.1.6 No repository field.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json has-binary-data@0.1.3 No repository field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json punycode@1.2.4 punycode is also the name of a node core module.
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.

    bufferutil@1.2.1 install d:\home\site\wwwroot\node_modules\bufferutil
    node-gyp rebuild

d:\home\site\wwwroot\node_modules\bufferutil>node "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Traceback (most recent call last):
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in
sys.exit(gyp.script_main())
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 534, in script_main
return main(sys.argv[1:])
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 527, in main
return gyp_main(args)
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 503, in gyp_main
options.circular_check)
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 98, in Load
generator.CalculateVariables(default_variables, params)
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1867, in CalculateVariables
generator_flags.get('msvs_version', 'auto'))
File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 402, in SelectVisualStudioVersion
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2015'

npm ERR! bufferutil@1.2.1 install: node-gyp rebuild
npm ERR! Exit status 1
An error has occurred during web site deployment.
npm ERR!
npm failed
npm ERR! Failed at the bufferutil@1.2.1 install script.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls bufferutil
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"
npm ERR! cwd d:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm WARN package.json object-component@0.0.3 No repository field.\r\nnpm WARN package.json parsejson@0.0.1 No repository field.\r\nnpm WARN package.json parsejson@0.0.1 No README data\r\nnpm WARN package.json parseuri@0.0.2 No repository field.\r\nnpm WARN package.json parseuri@0.0.2 No README data\r\nnpm WARN package.json parseqs@0.0.2 No repository field.\r\nnpm WARN package.json parseqs@0.0.2 No README data\r\nnpm WARN package.json callsite@1.0.0 No repository field.\r\nnpm WARN package.json has-binary@0.1.6 No repository field.\r\nnpm WARN package.json eyes@0.1.8 No repository field.\r\nnpm WARN package.json has-binary-data@0.1.3 No repository field.\r\nnpm WARN package.json indexof@0.0.1 No repository field.\r\nnpm WARN package.json punycode@1.2.4 punycode is also the name of a node core module.\r\nnpm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.\r\nTraceback (most recent call last):\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in \r\n sys.exit(gyp.script_main())\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 534, in script_main\r\n return main(sys.argv[1:])\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 527, in main\r\n return gyp_main(args)\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 503, in gyp_main\r\n options.circular_check)\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 98, in Load\r\n generator.CalculateVariables(default_variables, params)\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1867, in CalculateVariables\r\n generator_flags.get('msvs_version', 'auto'))\r\n File "c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 402, in SelectVisualStudioVersion\r\n versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)\r\nKeyError: '2015'\r\n\r\nnpm ERR! bufferutil@1.2.1 install: node-gyp rebuild\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the bufferutil@1.2.1 install script.\r\nnpm ERR! This is most likely a problem with the bufferutil package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR! node-gyp rebuild\r\nnpm ERR! You can get their info via:\r\nnpm ERR! npm owner ls bufferutil\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "d:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"\r\nnpm ERR! cwd d:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\nC:\Program Files (x86)\SiteExtensions\Kudu\52.50228.2109\bin\scripts\starter.cmd bash deploy.sh

Any ideas?
Do I need to do any of this?

    Login to github, enter your cgm-remote-monitor repository, click on package.json and then on the pen icon on the right side to edit it. Now go to "engines" section and delete the line which contains the text "node": "0.10.x" and save.
    On your Azure website dashboard, on the bottom right side, you will find the ftp site linked to your account, under "FTP HOST NAME" text. Using a ftp client, login to that ftp and enter your credentials as following: username is yourdomainname\yourusername , password is your azure password. After you login, navigate to wwwroot folder and delete iisnode.yml file.
    On your Azure website dashboard, go to "CONFIGURE" section, scroll down to "app settings" and modify the value present on the right side of "WEBSITE_NODE_DEFAULT_VERSION" to 0.10.40.
    Go to "DEPLOYMENTS" and click on "Sync" button located on the bottom of the page.

**Comment by LLLIEFA** [comment]
I removed the complete webapp in Azure, waited a few, and recreated it. This time it deployed successfully.
