### ISSUE TITLE
Tests fail sometimes

### ISSUE THREAD

**Issue by jontelm** [nightscout/cgm-remote-monitor#1587]
not ok 238 Throttle only update once when there are multiple posts
  AssertionError: expected 0 to be 3
      at Assertion.prop.(anonymous function) (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/should/lib/should.js:61:14)
      at Stream.dataWasLoaded (/home/travis/build/nightscout/cgm-remote-monitor/tests/api.treatments.test.js:33:47)
      at emitNone (events.js:85:20)
      at Stream.emit (events.js:179:7)
      at dataUpdated (/home/travis/build/nightscout/cgm-remote-monitor/lib/bootevent.js:9:3031)
      at loadComplete (/home/travis/build/nightscout/cgm-remote-monitor/lib/data/dataloader.js:9:1949)
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/async/lib/async.js:251:17
      at done (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/async/lib/async.js:132:19)
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/async/lib/async.js:32:16
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/async/lib/async.js:248:21
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/async/lib/async.js:572:34
      at /home/travis/build/nightscout/cgm-remote-monitor/lib/data/dataloader.js:9:10526
      at toArray (/home/travis/build/nightscout/cgm-remote-monitor/lib/devicestatus.js:9:2518)
      at handleCallback (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb/lib/utils.js:96:12)
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb/lib/cursor.js:835:16
      at handleCallback (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/cursor.js:159:5)
      at setCursorNotified (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/cursor.js:490:3)
      at /home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/cursor.js:561:16
      at queryCallback (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/cursor.js:241:5)
      at Callbacks.emit (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/topologies/server.js:116:3)
      at null.messageHandler (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/topologies/server.js:291:23)
      at Socket.<anonymous> (/home/travis/build/nightscout/cgm-remote-monitor/node_modules/mongodb-core/lib/connection/connection.js:285:22)
      at emitOne (events.js:90:13)
      at Socket.emit (events.js:182:7)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:531:20)
##

**Comment by MilosKozak** [comment]
it's common issue usualy caused by overloaded servers. Best solution found so far (for me) is to run it outside US working hours :)

**Comment by jasoncalabrese** [comment]
I think this is a bug in the test, that causes it to fail intermitently, would be great to find a fix for it
