### ISSUE TITLE
NS site stops displaying data after invalid devicestatus record

### ISSUE THREAD

**Issue by jmcrawford** [nightscout/cgm-remote-monitor#2343]
Nightscout site stops displaying any data after a devicestatus record is created with missing date openaps.iob.date field.  Nightscout displayed data again after deleting the database record.

Heroko shows this error:
2016-12-13T04:07:10.127669+00:00 app[web.1]: TypeError: Cannot read property 'time' of null
2016-12-13T04:07:10.127672+00:00 app[web.1]:     at fromDeviceStatus (/app/lib/plugins/iob.js:76:17)
2016-12-13T04:07:10.127673+00:00 app[web.1]:     at arrayMap (/app/node_modules/lodash/lodash.js:653:23)
2016-12-13T04:07:10.127674+00:00 app[web.1]:     at Function.map (/app/node_modules/lodash/lodash.js:9533:14)
2016-12-13T04:07:10.127676+00:00 app[web.1]:     at interceptor (/app/node_modules/lodash/lodash.js:16904:35)
2016-12-13T04:07:10.127678+00:00 app[web.1]:     at thru (/app/node_modules/lodash/lodash.js:8772:14)
2016-12-13T04:07:10.127679+00:00 app[web.1]:     at /app/node_modules/lodash/lodash.js:4389:28
2016-12-13T04:07:10.127679+00:00 app[web.1]:     at arrayReduce (/app/node_modules/lodash/lodash.js:697:21)
2016-12-13T04:07:10.127680+00:00 app[web.1]:     at baseWrapperValue (/app/node_modules/lodash/lodash.js:4388:14)
2016-12-13T04:07:10.127681+00:00 app[web.1]:     at LazyWrapper.lazyValue [as value] (/app/node_modules/lodash/lodash.js:1874:16)
2016-12-13T04:07:10.127682+00:00 app[web.1]:     at baseWrapperValue (/app/node_modules/lodash/lodash.js:4386:25)
2016-12-13T04:07:10.127683+00:00 app[web.1]:     at LodashWrapper.wrapperValue (/app/node_modules/lodash/lodash.js:9027:14)
2016-12-13T04:07:10.127683+00:00 app[web.1]:     at Object.lastIOBDeviceStatus (/app/lib/plugins/iob.js:67:8)
2016-12-13T04:07:10.127684+00:00 app[web.1]:     at Object.calcTotal (/app/lib/plugins/iob.js:29:22)
2016-12-13T04:07:10.127685+00:00 app[web.1]:     at setIOB (/app/lib/plugins/iob.js:20:18)
2016-12-13T04:07:10.127685+00:00 app[web.1]:     at Object.offerProperty (/app/lib/sandbox.js:111:19)
2016-12-13T04:07:10.127686+00:00 app[web.1]:     at Object.setProperties (/app/lib/plugins/iob.js:19:9)
2016-12-13T04:07:10.127687+00:00 app[web.1]:     at eachPlugin (/app/lib/plugins/index.js:123:16)
2016-12-13T04:07:10.127687+00:00 app[web.1]:     at arrayEach (/app/node_modules/lodash/lodash.js:530:11)
2016-12-13T04:07:10.127688+00:00 app[web.1]:     at Function.forEach (/app/node_modules/lodash/lodash.js:9319:14)
2016-12-13T04:07:10.127688+00:00 app[web.1]:     at Function.eachEnabledPlugin (/app/lib/plugins/index.js:98:7)
2016-12-13T04:07:10.127689+00:00 app[web.1]:     at Function.setProperties (/app/lib/plugins/index.js:121:13)
2016-12-13T04:07:10.127690+00:00 app[web.1]:     at Stream.updatePlugins (/app/lib/bootevent.js:105:19)
2016-12-13T04:07:10.127690+00:00 app[web.1]:     at Stream.emit (events.js:92:17)
2016-12-13T04:07:10.127691+00:00 app[web.1]:     at dataUpdated (/app/lib/bootevent.js:89:17)
2016-12-13T04:07:10.127691+00:00 app[web.1]:     at loadComplete (/app/lib/data/dataloader.js:45:7)
2016-12-13T04:07:10.127692+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:251:17
2016-12-13T04:07:10.127693+00:00 app[web.1]:     at done (/app/node_modules/async/lib/async.js:132:19)
2016-12-13T04:07:10.127693+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:32:16
2016-12-13T04:07:10.127694+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:248:21
2016-12-13T04:07:10.127694+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:572:34
2016-12-13T04:07:10.127695+00:00 app[web.1]:     at /app/lib/data/dataloader.js:140:5
2016-12-13T04:07:10.127695+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2016-12-13T04:07:10.127696+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/cursor.js:839:16
2016-12-13T04:07:10.127697+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
2016-12-13T04:07:10.127698+00:00 app[web.1]:     at setCursorDeadAndNotified (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:501:3)
2016-12-13T04:07:10.127698+00:00 app[web.1]:     at nextFunction (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:652:7)
2016-12-13T04:07:10.127699+00:00 app[web.1]:     at Cursor.next [as _next] (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:693:3)
2016-12-13T04:07:10.127699+00:00 app[web.1]:     at fetchDocs (/app/node_modules/mongodb/lib/cursor.js:835:10)
2016-12-13T04:07:10.127700+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/cursor.js:858:7
2016-12-13T04:07:10.127701+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
2016-12-13T04:07:10.127701+00:00 app[web.1]:     at nextFunction (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
2016-12-13T04:07:10.127702+00:00 app[web.1]:     at /app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:641:9
2016-12-13T04:07:10.127703+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:195:5)
2016-12-13T04:07:10.127704+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
2016-12-13T04:07:10.127704+00:00 app[web.1]:     at null.messageHandler (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:358:23)
2016-12-13T04:07:10.127705+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:211:18)
2016-12-13T04:07:10.127705+00:00 app[web.1]:     at Socket.emit (events.js:95:17)
2016-12-13T04:07:10.127706+00:00 app[web.1]:     at Socket.<anonymous> (_stream_readable.js:765:14)
2016-12-13T04:07:10.127707+00:00 app[web.1]:     at Socket.emit (events.js:92:17)
2016-12-13T04:07:10.127707+00:00 app[web.1]:     at emitReadable_ (_stream_readable.js:427:10)
2016-12-13T04:07:10.127708+00:00 app[web.1]:     at emitReadable (_stream_readable.js:423:5)
2016-12-13T04:07:10.127708+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:166:9)
2016-12-13T04:07:10.127709+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:128:10)
2016-12-13T04:07:10.127710+00:00 app[web.1]:     at TCP.onread (net.js:529:21)

devicestatus record that caused the problem:
{
    "_id": {
        "$oid": "584f5c9e6da62b0c00cf6b26"
    },
    "device": "openaps://raspberrypi",
    "openaps": {
        "iob": null,
        "suggested": {
            "temp": "absolute",
            "bg": 73,
            "tick": -6,
            "eventualBG": -71,
            "snoozeBG": 76,
            "predBGs": {
                "IOB": [
                    73,
                    63,
                    53,
                    45,
                    39,
                    39,
                    39,
                    39,
                    39,
                    39,
                    39,
                    39,
                    39
                ],
                "aCOB": [
                    73,
                    72,
                    73,
                    73,
                    74,
                    76,
                    78,
                    81,
                    84,
                    87,
                    90,
                    92,
                    94,
                    95,
                    96,
                    97,
                    99,
                    100,
                    102,
                    103,
                    105,
                    107,
                    108,
                    110,
                    111,
                    113,
                    115,
                    116,
                    118,
                    120,
                    121,
                    123,
                    125,
                    127,
                    128,
                    130,
                    131,
                    132,
                    133
                ]
            },
            "COB": 35,
            "IOB": 1.734,
            "reason": "COB: 35, Dev: -23, BGI: -6.78, ISF: 3.9, Target: 5.7; BG 4.1<4.3, but 21m left and 0 ~ req 0U/hr: no action required",
            "timestamp": "2016-12-13T02:25:20.000Z"
        },
        "enacted": {
            "bg": 79,
            "temp": "absolute",
            "snoozeBG": 49,
            "recieved": true,
            "rate": 0,
            "reason": "COB: 36, Dev: -44, BGI: -7.65, ISF: 3.9, Target: 5.7; Eventual BG -5.9 < 5.7, setting -2.525U/hr",
            "COB": 36,
            "eventualBG": -107,
            "timestamp": "2016-12-13T02:15:32.000Z",
            "duration": 30,
            "tick": -25,
            "IOB": 2.034
        }
    },
    "pump": {
        "clock": "2016-12-12T19:25:57-07:00",
        "battery": {
            "status": "normal",
            "voltage": 1.34
        },
        "reservoir": 82.125,
        "status": {
            "status": "normal",
            "bolusing": false,
            "suspended": false,
            "timestamp": "2016-12-13T02:25:16.000Z"
        }
    },
    "created_at": "2016-12-13T02:27:42.027Z"
}

**Comment by tomasboudr** [comment]
I had this same issue but with a different mongo DB collection: 

2017-02-09T21:40:46.186824+00:00 heroku[router]: at=info method=GET path="/api/v1/treatments.json?find[carbs][$exists]=true" host=tomns.herokuapp.com request_id=b8b8fcd5-14db-4199-ba79-dd2c0f8f6093 fwd="24.126.33.184" dyno=web.1 connect=1ms service=1932ms status=200 bytes=25854
2017-02-09T21:40:48.278798+00:00 app[web.1]: Load Complete:
2017-02-09T21:40:48.278811+00:00 app[web.1]: 	 sgvs:448, treatments:298, profiles:1, devicestatus:878, tempbasalTreatments:91, tempTargetTreatments:3
2017-02-09T21:40:48.571731+00:00 app[web.1]: TypeError: Cannot read property 'time' of null
2017-02-09T21:40:48.571742+00:00 app[web.1]:     at fromDeviceStatus (/app/lib/plugins/iob.js:82:17)
2017-02-09T21:40:48.571743+00:00 app[web.1]:     at arrayMap (/app/node_modules/lodash/lodash.js:660:23)
2017-02-09T21:40:48.571744+00:00 app[web.1]:     at Function.map (/app/node_modules/lodash/lodash.js:9571:14)
2017-02-09T21:40:48.571745+00:00 app[web.1]:     at interceptor (/app/node_modules/lodash/lodash.js:16970:35)
2017-02-09T21:40:48.571745+00:00 app[web.1]:     at thru (/app/node_modules/lodash/lodash.js:8812:14)
2017-02-09T21:40:48.571746+00:00 app[web.1]:     at /app/node_modules/lodash/lodash.js:4379:28
2017-02-09T21:40:48.571746+00:00 app[web.1]:     at arrayReduce (/app/node_modules/lodash/lodash.js:704:21)
2017-02-09T21:40:48.571747+00:00 app[web.1]:     at baseWrapperValue (/app/node_modules/lodash/lodash.js:4378:14)
2017-02-09T21:40:48.571748+00:00 app[web.1]:     at LazyWrapper.lazyValue [as value] (/app/node_modules/lodash/lodash.js:1880:16)
2017-02-09T21:40:48.571749+00:00 app[web.1]:     at baseWrapperValue (/app/node_modules/lodash/lodash.js:4376:25)
2017-02-09T21:40:48.571750+00:00 app[web.1]:     at LodashWrapper.wrapperValue (/app/node_modules/lodash/lodash.js:9067:14)
2017-02-09T21:40:48.571750+00:00 app[web.1]:     at Object.lastIOBDeviceStatus (/app/lib/plugins/iob.js:67:8)
2017-02-09T21:40:48.571751+00:00 app[web.1]:     at Object.calcTotal (/app/lib/plugins/iob.js:29:22)
2017-02-09T21:40:48.571751+00:00 app[web.1]:     at setIOB (/app/lib/plugins/iob.js:20:18)
2017-02-09T21:40:48.571752+00:00 app[web.1]:     at Object.offerProperty (/app/lib/sandbox.js:111:19)
2017-02-09T21:40:48.571752+00:00 app[web.1]:     at Object.setProperties (/app/lib/plugins/iob.js:19:9)
2017-02-09T21:40:48.571753+00:00 app[web.1]:     at eachPlugin (/app/lib/plugins/index.js:123:16)
2017-02-09T21:40:48.571753+00:00 app[web.1]:     at arrayEach (/app/node_modules/lodash/lodash.js:537:11)
2017-02-09T21:40:48.571754+00:00 app[web.1]:     at Function.forEach (/app/node_modules/lodash/lodash.js:9359:14)
2017-02-09T21:40:48.571755+00:00 app[web.1]:     at Function.eachEnabledPlugin (/app/lib/plugins/index.js:98:7)
2017-02-09T21:40:48.571755+00:00 app[web.1]:     at Function.setProperties (/app/lib/plugins/index.js:121:13)
2017-02-09T21:40:48.571756+00:00 app[web.1]:     at Stream.updatePlugins (/app/lib/bootevent.js:105:19)
2017-02-09T21:40:48.571757+00:00 app[web.1]:     at Stream.emit (events.js:92:17)
2017-02-09T21:40:48.571757+00:00 app[web.1]:     at dataUpdated (/app/lib/bootevent.js:89:17)
2017-02-09T21:40:48.571758+00:00 app[web.1]:     at loadComplete (/app/lib/data/dataloader.js:45:7)
2017-02-09T21:40:48.571758+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:251:17
2017-02-09T21:40:48.571759+00:00 app[web.1]:     at done (/app/node_modules/async/lib/async.js:132:19)
2017-02-09T21:40:48.571760+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:32:16
2017-02-09T21:40:48.571760+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:248:21
2017-02-09T21:40:48.571761+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:572:34
2017-02-09T21:40:48.571762+00:00 app[web.1]:     at /app/lib/data/dataloader.js:140:5
2017-02-09T21:40:48.571762+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:95:56)
2017-02-09T21:40:48.571763+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/cursor.js:852:16
2017-02-09T21:40:48.571763+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
2017-02-09T21:40:48.571764+00:00 app[web.1]:     at setCursorDeadAndNotified (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:505:3)
2017-02-09T21:40:48.571765+00:00 app[web.1]:     at nextFunction (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:651:7)
2017-02-09T21:40:48.571766+00:00 app[web.1]:     at Cursor.next [as _next] (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:692:3)
2017-02-09T21:40:48.571766+00:00 app[web.1]:     at fetchDocs (/app/node_modules/mongodb/lib/cursor.js:848:10)
2017-02-09T21:40:48.571767+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/cursor.js:871:7
2017-02-09T21:40:48.571768+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
2017-02-09T21:40:48.571768+00:00 app[web.1]:     at nextFunction (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:682:5)
2017-02-09T21:40:48.571769+00:00 app[web.1]:     at /app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:640:9
2017-02-09T21:40:48.571770+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:209:5)
2017-02-09T21:40:48.571771+00:00 app[web.1]:     at /app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:455:18
2017-02-09T21:40:48.571772+00:00 app[web.1]:     at process._tickDomainCallback (node.js:502:13)

**Comment by tomasboudr** [comment]
This just happened to me again...
