### ISSUE TITLE
Cannot deploy due to issue with module.js

### ISSUE THREAD

**Issue by tylergale** [nightscout/cgm-remote-monitor#2479]
Hi all.  I have followed the instructions to deploy Nightscout to an Azure website.  This includes forking the project into my own repository, and then deploying it to Azure.  Unfortunately, I cannot seem to get a deployment to work on Azure, and it's failing due to an error in module.js file (Nightscout file).

**Here is the error log:**
```
Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json mongodb@2.1.18 No README data
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> Nightscout@0.9.2 postinstall D:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install


module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
An error has occurred during web site deployment.
    at Function.Module._resolveFilename (module.js:338:15)
npm failed
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.9.2 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.9.2 postinstall script.
npm ERR! This is most likely a problem with the Nightscout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower --allow-root install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm WARN package.json mongodb@2.1.18 No README data\r\nnpm WARN deprecated node-uuid@1.4.7: use uuid module instead\r\n\r\nmodule.js:340\r\n    throw err;\r\n          ^\r\nError: Cannot find module 'q'\r\n    at Function.Module._resolveFilename (module.js:338:15)\r\n    at Function.Module._load (module.js:280:25)\r\n    at Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)\r\n    at Module._compile (module.js:456:26)\r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.Module._load (module.js:312:12)\r\n    at Module.require (module.js:364:17)\r\n\r\nnpm ERR! Nightscout@0.9.2 postinstall: `node node_modules/bower/bin/bower --allow-root install`\r\nnpm ERR! Exit status 8\r\nnpm ERR! \r\nnpm ERR! Failed at the Nightscout@0.9.2 postinstall script.\r\nnpm ERR! This is most likely a problem with the Nightscout package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     node node_modules/bower/bin/bower --allow-root install\r\nnpm ERR! You can get their info via:\r\nnpm ERR!     npm owner ls Nightscout\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! cwd D:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.60207.2684\bin\Scripts\starter.cmd bash deploy.sh
```
Can anyone recommend a fix for this, or should I fork an older version (and if so, is there a version people like to use).  Thanks!

**Comment by tylergale** [comment]
Closed as per discussion here: https://github.com/nightscout/cgm-remote-monitor/issues/1453

Might be worth mentioning this issue on the site, as the visible error is HTTP 500 (the site mentions only to check your connection strings, and not your Azure error logs).
