### ISSUE TITLE
Medtronic Guardian Connect

### ISSUE THREAD

**Issue by Schoggiweggli** [nightscout/cgm-remote-monitor#2508]
Hey, it it seems that the Minimed Connect feature unsurprisingly doesn't work with the newly released European version of Minimed Connect (Guardian Connect). I guess because the URL is different among other things ?. 

Otherwise it looks similar to US Minimed Connect.

**Comment by bogdangorescu** [comment]
You can replace the authentication server in US with the one on the EU, by modifying the corresponding strings in node_modules/minimed-connect-to-nightscout/carelink.js 
----
But this won't solve the issue! After fixing this first error, a  second error occurs, that has something to do with time interval. Here's the log:
`First error that was returned has something to do with the authentication server, so I changed everything from carelink.minimed.com to carelink.minimed.eu and this solved it.
The second error, which isn't that obvious to fix, has something to do with time interval.
This is the log:
Wed, 03 May 2017 12:28:20 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at app.js:52:22 RangeError: Invalid time value at timestampAsString (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:23:30) at deviceStatusEntry (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:66:16) at Object.module.exports [as transform] (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:129:20) at handleCarelinkData (/nfs/VM3/10000_medtronic/lib/plugins/mmconnect.js:55:33) at next (/nfs/VM3/10000_medtronic/node_modules/common/index.js:138:6) at Object.parseData (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:137:5) at next (/nfs/VM3/10000_medtronic/node_modules/common/index.js:138:6) at Request.<anonymous> (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:124:11) at Request._callback (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:55:8) at Request.self.callback (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:198:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:1063:14) at emitOne (events.js:101:20) at Request.emit (events.js:188:7) at Gunzip.<anonymous> (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:1009:12) at emitNone (events.js:91:20) at Gunzip.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)`

**Comment by shortanu** [comment]
solved in #3145
