### ISSUE TITLE
crash in share2nightscout-bridge 

### ISSUE THREAD

**Issue by bharat** [nightscout/cgm-remote-monitor#2523]
I'm getting a regular crash when trying to fetch data using share2nightsout-bridge. The crash looks like this:

```
/usr/www/website/cgm/node_modules/share2nightscout-bridge/index.js:217
        if (res.statusCode < 400) {
               ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/www/website/cgm/node_modules/share2nightscout-bridge/index.js:217:16)
    at self.callback (/usr/www/website/cgm/node_modules/share2nightscout-bridge/node_modules/request/request.js:344:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/www/website/cgm/node_modules/share2nightscout-bridge/node_modules/request/request.js:961:8) 
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:1013:8)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickDomainCallback (node.js:413:17)
```

I've modified my version of the code slightly to add some debug output so I can see what the result is. The only change is that I added line 216. Code looks like this:

```
   202  function engine (opts) {                                                                                                        
   203                                                                                                                                  
   204    var runs = 0;                                                                                                                 
   205    var failures = 0;                                                                                                             
   206    function my ( ) {                                                                                                             
   207      console.log('RUNNING', runs, 'failures', failures);                                                                         
   208      if (my.sessionID) {                                                                                                         
   209        var fetch_opts = Object.create(opts.fetch);                                                                               
   210        if (runs === 0) {                                                                                                         
   211          console.log('First run, fetching', opts.firstFetchCount);                                                               
   212          fetch_opts.maxCount = opts.firstFetchCount;                                                                             
   213        }                                                                                                                         
   214        fetch_opts.sessionID = my.sessionID;                                                                                      
   215        fetch(fetch_opts, function (err, res, glucose) {                                                                          
   216          if (err) { console.log([err, res, glucose]) }                                                                           
   217          if (res.statusCode < 400) {                                                                                             
   218            to_nightscout(glucose);                                                                                               
   219          } else {                                                                                                                
   220            my.sessionID = null;                                                                                                  
   221            refresh_token( );                                                                                                     
   222          }                                                                                                                       
   223        });                                                                                                                       
   224      } else {                                                                                                                    
   225        failures++;                                                                                                               
   226        refresh_token( );                                                                                                         
   227      }                                                                                                                           
   228    }                                                                                                                             
```

The output from that added debug line is:
```
[ { [Error: getaddrinfo EAI_AGAIN share1.dexcom.com:443]
    code: 'EAI_AGAIN',
    errno: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'share1.dexcom.com',
    host: 'share1.dexcom.com',
    port: 443 },
  undefined,
  undefined ]
```

I haven't dug any further - but happy to provide any useful data. This crash happens about once a week for me.

**Comment by BlakePetersen** [comment]
EAI_AGAIN is a connection timeout error. What environment is this error coming from (heroku/azure/local)?

**Comment by PieterGit** [comment]
@bharat and @BlakePetersen Can you create an issue or PR for this in the https://github.com/nightscout/share2nightscout-bridge/issues issue tracker? If there is a newer share2nightscout-bridge version we can include that in Nightscout. I'm closing this issue because of more than a year of inactivity. Please feel free to reopen it if there is more news.
