### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by rahulsamboo2** [nightscout/cgm-remote-monitor#2645]
I am getting the message below when trying to access my son's blood glucose on nightscout. Is it because my account has been flagged? If yes, I would appreciate if you could help.

Nightscout - Boot Error

Unable to connect to Mongo
    {"stack":"Error: double colon in host identifier
    at module.exports (D:\\home\\site\\wwwroot\
    ode_modules\\mongodb\\lib\\url_parser.js:91:13)
    at connect (D:\\home\\site\\wwwroot\
    ode_modules\\mongodb\\lib\\mongo_client.js:176:16)
    at Function.MongoClient.connect (D:\\home\\site\\wwwroot\
    ode_modules\\mongodb\\lib\\mongo_client.js:109:3)
    at connect_with_retry (D:\\home\\site\\wwwroot\\lib\\storage\\mongo-storage.js:31:28)
    at maybe_connect (D:\\home\\site\\wwwroot\\lib\\storage\\mongo-storage.js:51:7)
    at init (D:\\home\\site\\wwwroot\\lib\\storage\\mongo-storage.js:70:10)
    at setupStorage (D:\\home\\site\\wwwroot\\lib\\bootevent.js:73:43)
    at Object. (D:\\home\\site\\wwwroot\
    ode_modules\\bootevent\\index.js:12:7)
    at EventEmitter.saw.nest (D:\\home\\site\\wwwroot\
    ode_modules\\bootevent\
    ode_modules\\chainsaw\\index.js:86:12)
    at Object.acquire (D:\\home\\site\\wwwroot\
    ode_modules\\bootevent\\index.js:10:9)","message":"double colon in host identifier"}

**Comment by whooze** [comment]
Make sure you got your mongo-string correct in azure/heroku.

The message says something about double colon... I would take an extra look at that

**Comment by Breeze773** [comment]
Hi @rahulsamboo2 
Just in case you haven't been able to sort this out yet.  The mongo string can be a bit long and hard to read.

`mongodb://[app-user]:[app-password]@[mongodb-host-identifier]:39095/[some-other-non-obvious-string]`
If the error is right in that you have a problem in the host identifier, check before and after `[mongodb-host-identifier]` in this example, between the `@` sign and the port number, 39095, in this case.
