### ISSUE TITLE
Azure deploy Error: Cannot find module 'user-home'

### ISSUE THREAD

**Issue by padshiy8angel** [nightscout/cgm-remote-monitor#2709]
Stack:

```
Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Using start-up script server.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.11.1, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json mongodb@2.1.18 No README data
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> Nightscout@0.9.2 postinstall D:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install


module.js:340
    throw err;
          ^
Error: Cannot find module 'user-home'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.9.2 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.9.2 postinstall script.
npm ERR! This is most likely a problem with the Nightscout package,
An error has occurred during web site deployment.
npm ERR! not with npm itself.
npm failed
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower --allow-root install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
npm WARN pac
```

**Comment by PieterGit** [comment]
@padshiy8angel did you also try this with the Nightscout 0.10.x release?

**Comment by padshiy8angel** [comment]
YesОтправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail11.11.2017, 14:22, "PieterGit" <notifications@github.com>:@padshiy8angel did you also try this with the Nightscout 0.10.x release?
