### ISSUE TITLE
IOB calculation fails when "basal" plugin is enabled but no profile exists

### ISSUE THREAD

**Issue by tanja3981** [nightscout/cgm-remote-monitor#3331]
Bug on current "0.10.2-release-20171201" but probably longer.
Found when using alexa skill on a site where no profile was set (and not wanted).
Workaround is possible by disabling "basal" plugin, but as most people have enabled this by default we should fix it nevetheless.

2018-02-06T19:03:43.888242+00:00 app[web.1]: Incoming request from Alexa
2018-02-06T19:03:43.888463+00:00 app[web.1]: Received intent request
2018-02-06T19:03:43.888681+00:00 app[web.1]: {"name":"NSStatus","confirmationStatus":"NONE"}
2018-02-06T19:03:43.899886+00:00 app[web.1]: Rollup array for  Status
2018-02-06T19:03:43.900392+00:00 app[web.1]: [ { handler: [Function: alexaIOBRollupHandler],
2018-02-06T19:03:43.900395+00:00 app[web.1]:     name: 'current iob' },
2018-02-06T19:03:43.900397+00:00 app[web.1]:   { handler: [Function: alexaRollupCurrentBasalHandler],
2018-02-06T19:03:43.900399+00:00 app[web.1]:     name: 'current basal' },
2018-02-06T19:03:43.900401+00:00 app[web.1]:   { handler: [Function: bgRollupHandler], name: 'BG Status' } ]
2018-02-06T19:03:43.904159+00:00 app[web.1]: TypeError: Cannot read property 'toFixed' of undefined
2018-02-06T19:03:43.904163+00:00 app[web.1]:     at Object.toFixed (/app/lib/utils.js:32:25)
2018-02-06T19:03:43.904165+00:00 app[web.1]:     at getIob (/app/lib/plugins/iob.js:278:19)
2018-02-06T19:03:43.904167+00:00 app[web.1]:     at alexaIOBRollupHandler (/app/lib/plugins/iob.js:267:15)
2018-02-06T19:03:43.904168+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:567:21
2018-02-06T19:03:43.904170+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:246:17
2018-02-06T19:03:43.904172+00:00 app[web.1]:     at replenish (/app/node_modules/async/lib/async.js:191:21)
2018-02-06T19:03:43.904173+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:208:15
2018-02-06T19:03:43.904175+00:00 app[web.1]:     at _asyncMap (/app/node_modules/async/lib/async.js:245:13)
2018-02-06T19:03:43.904177+00:00 app[web.1]:     at Object.map (/app/node_modules/async/lib/async.js:222:23)
2018-02-06T19:03:43.904178+00:00 app[web.1]:     at _parallel (/app/node_modules/async/lib/async.js:565:20)
2018-02-06T19:03:44.264122+00:00 app[web.1]: [32mGRANTED: [0m 54.240.197.11 no-token api:*:read default

**Comment by tanja3981** [comment]
Pull request created: 
https://github.com/nightscout/cgm-remote-monitor/pull/3332

**Comment by tanja3981** [comment]
As PR is merged and closed this issue will also be closed.
