### ISSUE TITLE
Server restart on treatment upload with invalid id. 

### ISSUE THREAD

**Issue by tanja3981** [nightscout/cgm-remote-monitor#3462]
See discussion on facebook
https://www.facebook.com/groups/cgminthecloud/permalink/1561852763935974/

Reproducable on version 0.10.3-dev with any browser (firefox, chrome tested)

**Comment by tanja3981** [comment]
Stacktrace: 
2018-03-23T12:42:49.661845+00:00 app[web.1]: [32mWS: [0mdbUpdate client ID:  VPiJSwzLKdNwvIMZAAAA  data:  { collection: 'treatments',
2018-03-23T12:42:49.661857+00:00 app[web.1]:   _id: '1521758941450',
2018-03-23T12:42:49.661860+00:00 app[web.1]:   data: 
2018-03-23T12:42:49.661863+00:00 app[web.1]:    { eventType: 'Profile Switch',
2018-03-23T12:42:49.661865+00:00 app[web.1]:      duration: 0,
2018-03-23T12:42:49.661866+00:00 app[web.1]:      profile: 'Humalog ab 2018/01/26',
2018-03-23T12:42:49.661870+00:00 app[web.1]:      profileJson: '{"dia":"6","carbratio":[{"time":"00:00","value":"12","timeAsSeconds":"0"},{"time":"10:00","value":"8","timeAsSeconds":"36000"}],"carbs_hr":"20","delay":"20","sens":[{"time":"00:00","value":"40","timeAsSeconds":"0"},{"time":"02:00","value":"50","timeAsSeconds":"7200"},{"time":"04:00","value":"60","timeAsSeconds":"14400"},{"time":"06:00","value":"40","timeAsSeconds":"21600"},{"time":"09:00","value":"60","timeAsSeconds":"32400"},{"time":"14:00","value":"75","timeAsSeconds":"50400"},{"time":"16:00","value":"60","timeAsSeconds":"57600"},{"time":"17:00","value":"50","timeAsSeconds":"61200"},{"time":"23:00","value":"40","timeAsSeconds":"82800"}],"timezone":"Europe\\/Berlin","basal":[{"time":"00:00","value":"0.85","timeAsSeconds":"0"},{"time":"01:00","value":"0.95","timeAsSeconds":"3600"},{"time":"02:00","value":"0.75","timeAsSeconds":"7200"},{"time":"03:00","value":"0.7","timeAsSeconds":"10800"},{"time":"04:00","value":"0.65","timeAsSeconds":"14400"},{"time":"05:00","value":"0.6","timeAsSeconds":"18000"},{"time":"06:00","value":"0.85","timeAsSeconds":"21600"},{"time":"07:00","value":"0.95","timeAsSeconds":"25200"},{"time":"08:00","value":"0.9","timeAsSeconds":"28800"},{"time":"09:00","value":"0.7","timeAsSeconds":"32400"},{"time":"10:00","value":"0.65","timeAsSeconds":"36000"},{"time":"12:00","value":"0.6","timeAsSeconds":"43200"},{"time":"14:00","value":"0.5","timeAsSeconds":"50400"},{"time":"16:00","value":"0.5","timeAsSeconds":"57600"},{"time":"17:00","value":"0.6","timeAsSeconds":"61200"},{"time":"18:00","value":"0.7","timeAsSeconds":"64800"},{"time":"19:00","value":"0.7","timeAsSeconds":"68400"},{"time":"20:00","value":"0.6","timeAsSeconds":"72000"},{"time":"21:00","value":"0.65","timeAsSeconds":"75600"},{"time":"22:00","value":"0.75","timeAsSeconds":"79200"},{"time":"23:00","value":"0.8","timeAsSeconds":"82800"}],"target_low":[{"time":"00:00","value":"90","timeAsSeconds":"0"}],"target_high":[{"time":"00:00","value":"120","timeAsSeconds":"0"}],"startDate":"1970-01-01T00:00:00.000Z","units":"mg\\/dl"}',
2018-03-23T12:42:49.661872+00:00 app[web.1]:      created_at: '2018-03-22T22:48:52Z',
2018-03-23T12:42:49.661874+00:00 app[web.1]:      enteredBy: 'AndroidAPS',
2018-03-23T12:42:49.661875+00:00 app[web.1]:      NSCLIENT_ID: 1521758941491 } }
2018-03-23T12:42:49.663857+00:00 app[web.1]: /app/node_modules/bson/lib/bson/objectid.js:50
2018-03-23T12:42:49.663862+00:00 app[web.1]:     throw new Error("Argument passed in must be a single String of 12 bytes or a string of 24 hex characters");
2018-03-23T12:42:49.663864+00:00 app[web.1]:     ^
2018-03-23T12:42:49.663866+00:00 app[web.1]: 
2018-03-23T12:42:49.663867+00:00 app[web.1]: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
2018-03-23T12:42:49.663870+00:00 app[web.1]:     at new ObjectID (/app/node_modules/bson/lib/bson/objectid.js:50:11)
2018-03-23T12:42:49.663873+00:00 app[web.1]:     at Socket.dbUpdate (/app/lib/server/websocket.js:191:20)
2018-03-23T12:42:49.663875+00:00 app[web.1]:     at emitTwo (events.js:126:13)
2018-03-23T12:42:49.663876+00:00 app[web.1]:     at Socket.emit (events.js:214:7)
2018-03-23T12:42:49.663878+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:503:12
2018-03-23T12:42:49.663880+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-03-23T12:42:49.663881+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-03-23T12:42:49.678945+00:00 app[web.1]: error: Forever detected script exited with code: 1
2018-03-23T12:42:49.683683+00:00 app[web.1]: error: Script restart attempt #1

**Comment by tanja3981** [comment]
Created pull request which will fix it. 
Tested with my current AndroidAPS setting where the faulty profile switch was still in the upload queue.

**Comment by tanja3981** [comment]
Merged with linked PR.
