### ISSUE TITLE
Deployment on Windows is broken

### ISSUE THREAD

**Issue by jaylagorio** [nightscout/cgm-remote-monitor#3504]
Good evening!

I'm attempting to migrate my existing Windows install, version 0.10.2-release-20171201
head 75e195a0, to a different system. Everything was going well until I encountered the following error when doing ``npm install``:

```
[Cut lots and lots of log lines]
102528 info postinstall handlebars@4.0.10
102529 verbose unlock done using C:\Users\Administrator.LAGORIO\AppData\Roaming\npm-cache\_locks\handlebars-cde971dceb2242c1.lock for C:\Nightscout\node_modules\handlebars
102530 verbose write writing to C:\Nightscout\node_modules\caniuse-db\package.json
102531 info preinstall caniuse-db@1.0.30000726
102532 verbose readDependencies loading dependencies from C:\Nightscout\node_modules\caniuse-db\package.json
102533 verbose readDependencies loading dependencies from C:\Nightscout\node_modules\caniuse-db\package.json
102534 silly install resolved []
102535 verbose about to build C:\Nightscout\node_modules\caniuse-db
102536 info build C:\Nightscout\node_modules\caniuse-db
102537 info linkStuff caniuse-db@1.0.30000726
102538 silly linkStuff caniuse-db@1.0.30000726 has C:\Nightscout\node_modules as its parent node_modules
102539 verbose linkBins caniuse-db@1.0.30000726
102540 verbose linkMans caniuse-db@1.0.30000726
102541 verbose rebuildBundles caniuse-db@1.0.30000726
102542 info install caniuse-db@1.0.30000726
102543 info postinstall caniuse-db@1.0.30000726
102544 verbose unlock done using C:\Users\Administrator.LAGORIO\AppData\Roaming\npm-cache\_locks\caniuse-db-8e8cd88f024ca292.lock for C:\Nightscout\node_modules\caniuse-db
102545 verbose stack Error: Unsupported
102545 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:47:14)
102545 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
102545 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
102545 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
102545 verbose stack     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:26:10)
102545 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
102545 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
102545 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
102545 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:1038:5
102545 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\locker.js:39:7
102546 verbose pkgid fsevents@1.1.3
102547 verbose cwd C:\Nightscout
102548 error Windows_NT 10.0.14393
102549 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013"
102550 error node v0.12.10
102551 error npm  v2.14.9
102552 error code EBADPLATFORM
102553 error notsup Unsupported
102553 error notsup Not compatible with your operating system or architecture: fsevents@1.1.3
102553 error notsup Valid OS:    darwin
102553 error notsup Valid Arch:  any
102553 error notsup Actual OS:   win32
102553 error notsup Actual Arch: x64
102554 verbose exit [ 1, true ]
```

It looks like a required dependency on ``fsevents`` was taken since 0.10.2-release-20171201 released and that package doesn't support non-Mac platforms. Is there a workaround available?

**Comment by sulkaharo** [comment]
Can you try to add the package using NPM to see if the deploy succeeds? (Run `npm install fsevents` in the folder, then re-deploy.)

**Comment by jaylagorio** [comment]
I ran that and this is the output in its entirety (and seems to rail on the fact that this isn't a Mac):

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fsevents"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Nightscout\npm-debug.log
```

**Comment by jaylagorio** [comment]
Any word on what I can do to get around this?

**Comment by jaylagorio** [comment]
Using ``require-analyzer`` (https://blog.nodejitsu.com/analyze-nodejs-dependencies-like-magic/) does not reveal anything about ``fsevents``. Is the only way to find out who took a dependency on this thing to go to the NPM package page and compare all 1200 packages that depend on it to the several hundred packages in the list above?

**Comment by jaylagorio** [comment]
Grepped the directory. ``npm-shrinkwrap.js`` shows the culprit to be ``chokidar``:

```
"chokidar": {
      "version": "1.7.0",
      "resolved": "https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz",
      "integrity": "sha1-eY5ol3gVHIB2tLNg5e3SjNortGg=",
      "requires": {
        "anymatch": "1.3.0",
        "async-each": "1.0.1",
        "fsevents": "1.1.3",
        "glob-parent": "2.0.0",
        "inherits": "2.0.3",
        "is-binary-path": "1.0.1",
        "is-glob": "2.0.1",
        "path-is-absolute": "1.0.1",
        "readdirp": "2.1.0"
      }
    }
```

The only thing is that later in the file ``fsevents`` is labeled as optional:

```
"fsevents": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz",
      "integrity": "sha512-WIr7iDkdmdbxu/Gh6eKEZJL6KPE74/5MEsf2whTOFNxbIoIixogroLdKYqB6FDav4Wavh/lZdzzd3b2KxIXC5Q==",
      "optional": true,
      "requires": {
        "nan": "2.8.0",
        "node-pre-gyp": "0.6.39"
      }
```

Now knowing where the dependency lies still doesn't help because ``fsevents`` is marked optional anyway. Why isn't it being treated that way during install?

**Comment by PieterGit** [comment]
@jaylagorio `fsevents` and `chokidar` are required for `forever`. This is only used in the Procfile for Heroku and I think it can be removed. I started a PR but that needs more work (help wanted), see
https://github.com/nightscout/cgm-remote-monitor/pull/3641
If you are lucky we can include this in the 0.10.3 release but I'm not sure if it's that easy.

I'm closing this issue, and we should continue in the PR to support Windows.

**Comment by jaylagorio** [comment]
Glad to see you have changes in the queue. Let me pull that branch this weekend and run through my setup steps to see how they work. Thanks!

**Comment by PieterGit** [comment]
I seem to be able to use Nightscout under Windows with https://github.com/nightscout/cgm-remote-monitor/pull/3675 
Since I don't use Nightscout under Windows I haven't done a lot of testing, but all testcases pass and I am able to start Nightscout and  open it in a browser without problems

**Comment by jaylagorio** [comment]
Confirming that I can deploy and start Nightscout then load it in a browser with #3675!
