### ISSUE TITLE
Nightscout crashes on startup

### ISSUE THREAD

**Issue by renegadeandy** [nightscout/cgm-remote-monitor#3836]
Version information:

Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Nightscout@0.10.3-master-20180805 start: `node server.js`

I have just run `npm install`, which finished successfully.

When I run `npm start` I get the following output:

```
:~/cgm-remote-monitor$ npm start

> Nightscout@0.10.3-master-20180805 start /home/andy/cgm-remote-monitor
> node server.js

Setting up new connection to MongoDB
Successfully established a connected to MongoDB
Mongo Storage system ready
Plugins registered [ { name: 'bgnow',
    label: 'BG Now',
    pluginType: 'pill-primary',
    mostRecentBucket: [Function: mostRecentBucket],
    previousBucket: [Function: previousBucket],
    setProperties: [Function: setProperties],
    fillBuckets: [Function: fillBuckets],
    analyzeBucket: [Function: analyzeBucket],
    calcDelta: [Function: calcDelta],
    updateVisualisation: [Function: updateVisualisation],
    enabled: true },
  { name: 'direction',
    label: 'BG direction',
    pluginType: 'bg-status',
    setProperties: [Function: setProperties],
    updateVisualisation: [Function: updateVisualisation],
    info: [Function: info],
    enabled: true },
  { name: 'upbat',
    label: 'Uploader Battery',
    pluginType: 'pill-status',
    pillFlip: true,
    getPrefs: [Function: getPrefs],
    setProperties: [Function: setProperties],
    analyzeData: [Function: analyzeData],
    checkNotifications: [Function: checkNotifications],
    updateVisualisation: [Function: updateVisualisation],
    alexa: { intentHandlers: [Object] },
    enabled: true },
  { name: 'ar2',
    label: 'AR2',
    pluginType: 'forecast',
    setProperties: [Function: setProperties],
    checkNotifications: [Function: checkNotifications],
    forecast: [Function: forecast],
    updateVisualisation: [Function: updateVisualisation],
    forecastCone: [Function: forecastCone],
    alexa: { intentHandlers: [Object] },
    enabled: true },
  { name: 'errorcodes',
    label: 'Dexcom Error Codes',
    pluginType: 'notification',
    toDisplay: [Function: toDisplay],
    checkNotifications: [Function: checkNotifications],
    buildMappingFromSettings: [Function: buildMappingFromSettings],
    enabled: true },
  { name: 'timeago',
    label: 'Timeago',
    pluginType: 'pill-status',
    pillFlip: true,
    checkNotifications: [Function: checkNotifications],
    checkStatus: [Function: checkStatus],
    isMissing: [Function: isMissing],
    inTheFuture: [Function: inTheFuture],
    almostInTheFuture: [Function: almostInTheFuture],
    isLessThan: [Function: isLessThan],
    resolvers: 
     [ [Function: isMissing],
       [Function: inTheFuture],
       [Function: almostInTheFuture],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function] ],
    calcDisplay: [Function: calcDisplay],
    updateVisualisation: [Function: updateVisualisation],
    enabled: true } ]
Pushover was NOT configured
Ensuring indexes
ensuring index for: date
ensuring index for: type
ensuring index for: sgv
ensuring index for: mbg
ensuring index for: sysTime
ensuring index for: dateString
ensuring index for: created_at
ensuring index for: eventType
ensuring index for: insulin
ensuring index for: carbs
ensuring index for: glucose
ensuring index for: enteredBy
ensuring index for: boluscalc.foods._id
ensuring index for: notes
ensuring index for: NSCLIENT_ID
ensuring index for: percent
ensuring index for: absolute
ensuring index for: duration
ensuring index for: created_at
ensuring index for: NSCLIENT_ID
ensuring index for: startDate
ensuring index for: type
ensuring index for: position
ensuring index for: hidden
ensuring index for: created_at
Dexcom bridge not enabled
MiniMed Connect not enabled
tick 2018-08-14T13:28:35.746Z
/home/andy/cgm-remote-monitor/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/andy/cgm-remote-monitor/tmp/cacheBusterToken'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at create (/home/andy/cgm-remote-monitor/app.js:24:33)
    at booted (/home/andy/cgm-remote-monitor/server.js:49:31)
    at Object.boot (/home/andy/cgm-remote-monitor/node_modules/bootevent/index.js:46:9)
    at saw.next (/home/andy/cgm-remote-monitor/node_modules/chainsaw/index.js:62:18)
    at finishBoot (/home/andy/cgm-remote-monitor/lib/server/bootevent.js:226:5)
    at Object.<anonymous> (/home/andy/cgm-remote-monitor/node_modules/bootevent/index.js:12:7)
    at EventEmitter.saw.nest (/home/andy/cgm-remote-monitor/node_modules/chainsaw/index.js:86:12)

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Nightscout@0.10.3-master-20180805 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Nightscout@0.10.3-master-20180805 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Nightscout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Nightscout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/cgm-remote-monitor/npm-debug.log
```
This is the content of npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Nightscout@0.10.3-master-20180805~prestart: Nightscout@0.10.3-master-20180805
6 silly lifecycle Nightscout@0.10.3-master-20180805~prestart: no script for prestart, continuing
7 info lifecycle Nightscout@0.10.3-master-20180805~start: Nightscout@0.10.3-master-20180805
8 verbose lifecycle Nightscout@0.10.3-master-20180805~start: unsafe-perm in lifecycle true
9 verbose lifecycle Nightscout@0.10.3-master-20180805~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/andy/cgm-remote-monitor/node_modules/.bin:/home/andy/bin:/home/andy/.local/bin:/home/andy/.rbenv/plugins/ruby-build/bin:/home/andy/.rbenv/shims:/home/andy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle Nightscout@0.10.3-master-20180805~start: CWD: /home/andy/cgm-remote-monitor
11 silly lifecycle Nightscout@0.10.3-master-20180805~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle Nightscout@0.10.3-master-20180805~start: Returned: code: 1  signal: null
13 info lifecycle Nightscout@0.10.3-master-20180805~start: Failed to exec start script
14 verbose stack Error: Nightscout@0.10.3-master-20180805 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid Nightscout@0.10.3-master-20180805
16 verbose cwd /home/andy/cgm-remote-monitor
17 error Linux 4.4.0-93-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Nightscout@0.10.3-master-20180805 start: `node server.js`
22 error Exit status 1
23 error Failed at the Nightscout@0.10.3-master-20180805 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Nightscout package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Nightscout
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Nightscout
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
This happens everytime I launch nightscout.

All help would be appreciated.

**Comment by sulkaharo** [comment]
Nightscout requires Node 8 and a newer NPM version. You’re probably self-hosting? Try upgrading both and it should work.

**Comment by PieterGit** [comment]
Closing issue. Node 6 is not supported. Please upgrade Node and Npm. See instructions if 
https://github.com/nightscout/cgm-remote-monitor/#install

If you have more problems please reopen or ask for help at https://gitter.im/nightscout/public
