### ISSUE TITLE
Crash on startup (cacheBusterToken)

### ISSUE THREAD

**Issue by Meekelis** [nightscout/cgm-remote-monitor#4366]
**Describe the bug**
Cgm-remote-monitor crashes on starting server.js. 
`Error: ENOENT: no such file or directory, open '/home/nightscout/nightscout/cgm-remote-monitor/tmp/cacheBusterToken'`

**Environment**
```
MongoDB shell version: 3.2.11
nightscout@b9feb:~/nightscout/cgm-remote-monitor$ node -v
v10.15.1
nightscout@b9feb:~/nightscout/cgm-remote-monitor$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Start script**
```
#!/bin/bash

# environment variables
export DISPLAY_UNITS="mmol"
export MONGO_CONNECTION="mongodb://****:****@localhost:27017/Nightscout"
export BASE_URL="https://***.***.***.***"
export PORT=80
export API_SECRET="****"

# export PUMP_FIELDS="reservoir battery status"
export DEVICESTATUS_ADVANCED=true
export ENABLE="careportal"

export TIME_FORMAT=24

# start server
node server.js
```

**Output**
```
nightscout@b9feb:~/nightscout/cgm-remote-monitor$ ./start.sh
Node version v10.15.1 is supported
Setting up new connection to MongoDB
Successfully established a connected to MongoDB
Mongo Storage system ready
Plugins registered [ { name: 'bgnow',
    label: 'BG Now',
    pluginType: 'pill-primary',
    mostRecentBucket: [Function: mostRecentBucket],
    previousBucket: [Function: previousBucket],
    setProperties: [Function: setProperties],
    fillBuckets: [Function: fillBuckets],
    analyzeBucket: [Function: analyzeBucket],
    calcDelta: [Function: calcDelta],
    updateVisualisation: [Function: updateVisualisation],
    enabled: true },
  { name: 'direction',
    label: 'BG direction',
    pluginType: 'bg-status',
    setProperties: [Function: setProperties],
    updateVisualisation: [Function: updateVisualisation],
    info: [Function: info],
    enabled: true },
  { name: 'upbat',
    label: 'Uploader Battery',
    pluginType: 'pill-status',
    pillFlip: true,
    getPrefs: [Function: getPrefs],
    setProperties: [Function: setProperties],
    analyzeData: [Function: analyzeData],
    checkNotifications: [Function: checkNotifications],
    updateVisualisation: [Function: updateVisualisation],
    alexa: { intentHandlers: [Array] },
    enabled: true },
  { name: 'ar2',
    label: 'AR2',
    pluginType: 'forecast',
    setProperties: [Function: setProperties],
    checkNotifications: [Function: checkNotifications],
    forecast: [Function: forecast],
    updateVisualisation: [Function: updateVisualisation],
    forecastCone: [Function: forecastCone],
    alexa: { intentHandlers: [Array] },
    enabled: true },
  { name: 'errorcodes',
    label: 'Dexcom Error Codes',
    pluginType: 'notification',
    toDisplay: [Function: toDisplay],
    checkNotifications: [Function: checkNotifications],
    buildMappingFromSettings: [Function: buildMappingFromSettings],
    enabled: true },
  { name: 'treatmentnotify',
    label: 'Treatment Notifications',
    pluginType: 'notification',
    checkNotifications: [Function: checkNotifications],
    enabled: true },
  { name: 'timeago',
    label: 'Timeago',
    pluginType: 'pill-status',
    pillFlip: true,
    checkNotifications: [Function: checkNotifications],
    checkStatus: [Function: checkStatus],
    isMissing: [Function: isMissing],
    inTheFuture: [Function: inTheFuture],
    almostInTheFuture: [Function: almostInTheFuture],
    isLessThan: [Function: isLessThan],
    resolvers:
     [ [Function: isMissing],
       [Function: inTheFuture],
       [Function: almostInTheFuture],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function: checkIsLessThan],
       [Function] ],
    calcDisplay: [Function: calcDisplay],
    updateVisualisation: [Function: updateVisualisation],
    enabled: true } ]
Pushover was NOT configured
Ensuring indexes
ensuring index for: date
ensuring index for: type
ensuring index for: sgv
ensuring index for: mbg
ensuring index for: sysTime
ensuring index for: dateString
ensuring index for: created_at
ensuring index for: eventType
ensuring index for: insulin
ensuring index for: carbs
ensuring index for: glucose
ensuring index for: enteredBy
ensuring index for: boluscalc.foods._id
ensuring index for: notes
ensuring index for: NSCLIENT_ID
ensuring index for: percent
ensuring index for: absolute
ensuring index for: duration
ensuring index for: created_at
ensuring index for: NSCLIENT_ID
ensuring index for: startDate
ensuring index for: type
ensuring index for: position
ensuring index for: hidden
ensuring index for: created_at
Dexcom bridge not enabled
MiniMed Connect not enabled
tick 2019-02-15T16:43:50.502Z
Security settings: INSECURE_USE_HTTP= false , SECURE_HSTS_HEADER= true
(node:5992) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
/home/nightscout/nightscout/cgm-remote-monitor/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/nightscout/nightscout/cgm-remote-monitor/tmp/cacheBusterToken'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at create (/home/nightscout/nightscout/cgm-remote-monitor/app.js:57:33)
    at booted (/home/nightscout/nightscout/cgm-remote-monitor/server.js:49:31)
    at Object.boot (/home/nightscout/nightscout/cgm-remote-monitor/node_modules/bootevent/index.js:46:9)
    at saw.next (/home/nightscout/nightscout/cgm-remote-monitor/node_modules/chainsaw/index.js:62:18)
    at finishBoot (/home/nightscout/nightscout/cgm-remote-monitor/lib/server/bootevent.js:263:5)
    at Object.<anonymous> (/home/nightscout/nightscout/cgm-remote-monitor/node_modules/bootevent/index.js:12:7)
    at EventEmitter.saw.nest (/home/nightscout/nightscout/cgm-remote-monitor/node_modules/chainsaw/index.js:86:12)
    at Object.acquire (/home/nightscout/nightscout/cgm-remote-monitor/node_modules/bootevent/index.js:10:9)
nightscout@b9feb:~/nightscout/cgm-remote-monitor$
```

**Other**
Cloned today from:
`https://github.com/nightscout/cgm-remote-monitor.git`

Unsure how to reproduce. New to node.js and Nightscout. Any help appreciated.

**Comment by Meekelis** [comment]
`touch cgm-remote-monitor/tmp/cacheBusterToken` solves issue with no immediate consequences.

**Comment by sulkaharo** [comment]
This sounds like you’ve run npm as root when installing Nightscout. Chown all the files to the right user (www?) and run npm install as that user and it’ll work

**Comment by Meekelis** [comment]
That's exactly right.

**Comment by PieterGit** [comment]
Closing PR. Reporter @Meekelis report he installed it as root as @sulkaharo suggests.

@Meekelis if you can improve the docs, like https://github.com/nightscout/cgm-remote-monitor/blob/dev/README.md please do and create a PR. It currently lists
"As a non-root user clone this repo then install dependencies into the root of the project:". I agree it can be made more clear in the docs so that people don't miss it.

**Comment by skalahonza** [comment]
This happened to me too, when I used the deploy to Azure button. I suggest you add some sanity check, if the file does not exist, create it. Also, make sure you are not using Azure App Service zip deploy, because that makes the file system readonly.
