### ISSUE TITLE
Windows build support broken in 0.12.5 (since it broke in 0.12.3)

### ISSUE THREAD

**Issue by jaylagorio** [nightscout/cgm-remote-monitor#4843]
After a `git pull` from an 0.12.2 directory or a `git clone` in a new empty directory, `npm install` fails to build Nightscout at the `heapdump` dependency. This worked as recently as last week with 0.12.2. Command line and output:

```
C:\Nightscout>npm install

> heapdump@0.3.14 install C:\Nightscout\node_modules\heapdump
> node-gyp rebuild


C:\Nightscout\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Nightscout\node_modules\heapdump\build\..\src\compat-inl.h
C:\Nightscout\node_modules\heapdump\build\..\src\compat.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(2570): error C2144: syntax error : 'int' should be p
receded by ';' [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(2570): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4273): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function w
hich can be defaulted [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4276): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)'
: is not a special member function which can be defaulted [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4362): error C2610: 'v8::WasmModuleObjectBuilderStre
aming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function wh
ich can be defaulted [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4367): error C2610: 'v8::WasmModuleObjectBuilderStre
aming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special me
mber function which can be defaulted [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4632): error C2146: syntax error : missing ';' befor
e identifier 'size_t' [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
c:\users\scoutuser\.node-gyp\10.15.2\include\node\v8.h(4632): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h
': No such file or directory [C:\Nightscout\node_modules\heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Nightscout\node_modules\heapdump
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.2 requires a peer of eslint@>=1.6.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\nodemon\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scoutuser\AppData\Roaming\npm-cache\_logs\2019-08-02T00_54_39_873Z-debug.log
```

**Comment by martinachtman** [comment]
I've encountered the same behavior with _docker build_ and fixed it by adding build packages **python, make** and **g++** to node:10-alpine:
`$ cat Dockerfile
FROM node:10-alpine

MAINTAINER Nightscout Contributors

RUN mkdir -p /opt/app && \
    apk add --no-cache --virtual build-dependencies \
    python \
    make \
    g++
ADD . /opt/app
WORKDIR /opt/app
RUN chown -R node:node /opt/app
USER node

RUN npm install && \
  npm run postinstall && \
  npm run env && \
  npm audit fix

EXPOSE 1337

CMD ["node", "server.js"]
`

**Comment by jaylagorio** [comment]
I've added MinGW, which includes *make* and *g++*, to the environment which already contained Python. The error persists.

**Comment by jaylagorio** [comment]
Windows build support still broken in 0.12.5:

```
C:\Nightscout0125>npm install

> heapdump@0.3.15 install C:\Nightscout0125\node_modules\heapdump
> node-gyp rebuild


C:\Nightscout0125\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Nightscout0125\node_modules\heapdump\build\..\src\compat-inl.h
C:\Nightscout0125\node_modules\heapdump\build\..\src\compat.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  heapdump.cc
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2570): error C2144: syntax error : 'int' should be p
receded by ';' [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(2570): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4273): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function w
hich can be defaulted [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4276): error C2610: 'v8::WasmCompiledModule::Transfe
rrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)'
: is not a special member function which can be defaulted [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4362): error C2610: 'v8::WasmModuleObjectBuilderStre
aming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function wh
ich can be defaulted [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4367): error C2610: 'v8::WasmModuleObjectBuilderStre
aming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special me
mber function which can be defaulted [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4632): error C2146: syntax error : missing ';' befor
e identifier 'size_t' [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
c:\users\administrator\.node-gyp\10.15.2\include\node\v8.h(4632): error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h
': No such file or directory [C:\Nightscout0125\node_modules\heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Nightscout0125\node_modules\heapdump
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heapdump@0.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jaylagorio** [comment]
The solution is to install Visual Studio 2015 Express (or another edition) and run `npm install --msvs_version=2015`. I will add this to the docs when I can.
