### ISSUE TITLE
Memory quota exceeded - no new data

### ISSUE THREAD

**Issue by matti05** [nightscout/cgm-remote-monitor#6273]
**Describe the bug**
Nightscout doesn't get new data. "Restart all dynos" is required every few days. 
Heroku's log indicates a problem with memory limit.
```
2020-10-19T11:08:05.401844+00:00 heroku[web.1]: Process running mem=869M(169.7%)
2020-10-19T11:08:05.404093+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2020-10-19T11:08:18.218118+00:00 app[web.1]: MiniMed Connect error: Error: connect ECONNRESET 144.15.107.20:443
2020-10-19T11:08:18.218129+00:00 app[web.1]: stack: Error: connect ECONNRESET 144.15.107.20:443
2020-10-19T11:08:18.218129+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-10-19T11:08:28.688003+00:00 heroku[web.1]: Process running mem=870M(169.9%)
2020-10-19T11:08:28.691374+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2020-10-19T11:08:30.368602+00:00 app[web.1]: tick 2020-10-19T11:08:30.367Z
2020-10-19T11:08:49.004069+00:00 heroku[web.1]: Process running mem=870M(169.9%)
2020-10-19T11:08:49.005870+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2020-10-19T11:08:56.204274+00:00 app[web.1]: [32mWS: [0mDisconnected client ID:  h5XC9S7OpgAV6o90AAAG
2020-10-19T11:08:57.572137+00:00 app[web.1]: MiniMed Connect error: Error: write ECONNRESET
2020-10-19T11:08:57.572164+00:00 app[web.1]: stack: Error: write ECONNRESET
2020-10-19T11:08:57.572165+00:00 app[web.1]:     at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
2020-10-19T11:08:57.670681+00:00 app[web.1]: MiniMed Connect error: Error: write ECONNRESET
2020-10-19T11:08:57.670687+00:00 app[web.1]: stack: Error: write ECONNRESET
2020-10-19T11:08:57.670688+00:00 app[web.1]:     at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
2020-10-19T11:08:57.705798+00:00 app[web.1]: MiniMed Connect error: Error: write ECONNRESET
2020-10-19T11:08:57.705801+00:00 app[web.1]: stack: Error: write ECONNRESET
2020-10-19T11:08:57.705802+00:00 app[web.1]:     at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
2020-10-19T11:08:57.716227+00:00 app[web.1]: MiniMed Connect error: Error: write ECONNRESET
2020-10-19T11:08:57.716229+00:00 app[web.1]: stack: Error: write ECONNRESET
2020-10-19T11:08:57.716230+00:00 app[web.1]:     at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
```

**Your setup information**
- Nightscout 14.0.6
- Guardian Connect - data pulled from Carelink
- Loop

Some people reported this problem as well.
https://www.facebook.com/groups/cgminthecloud/permalink/3442258475895384/

**Comment by sulkaharo** [comment]
870MB is pretty extreme memory consumption, wonder what's up with that - I'm monitoring multiple instances and they don't exhibit this. Do you get these errors all the time with Minimed? Wonder if that's causing a memory leak. Also just to make sure, is this vanilla 14.0.6 or have you edited the package.json as part of the deployment?

**Comment by dacia1300** [comment]
Setup:
Nightscout 14.0.6- vanilla without any modifications.
Guardian Connect CGM- data pulled from Carelink 
Pebble smartwatch.
Heroku Setup: 
Enable : careportal basal iob cob cors sage mmconnect
Show_Plugins: careportal iob cob
The crashes are not often. last crash was in 19th of October.
![1](https://user-images.githubusercontent.com/67636834/96723576-60dd7080-13b7-11eb-8a4e-02c9705fd866.jpg)

**Comment by matti05** [comment]
I have these crashes about twice a week. I modified only arrow in direction.js.

**Comment by sulkaharo** [comment]
Can you please test the latest DEV asap, it should fix any issues with mmconnect

**Comment by dacia1300** [comment]
I  am one of the EU users for whom nightscout does not work anymore due to CareLink EU blocking all requests from Heroku Europe.
I just tried the latest DEV to see if this fixes it. It did not work.
These are the steps I used to try it:
1. Added mmconnect in the Enable field in Heroku.
2. Chose the dev branch in Github.
3. In heroku > Deploy> Disconnected > Reconnected to Github.
4. In the Manual deploy section I chose the Dev branch.
5. Tapped the Deploy Branch Button.
6. Restart all Dynos.
![2](https://user-images.githubusercontent.com/67636834/103444239-7d2b4280-4c6f-11eb-95cf-5dc897c27fa6.jpg)
![Error](https://user-images.githubusercontent.com/67636834/103444240-7f8d9c80-4c6f-11eb-9371-18122fed80f5.png)

**Comment by sulkaharo** [comment]
Right - if Heroku Europe is being blocked, you'll have to redeploy the site to another region. :(
