### ISSUE TITLE
MMCONNECT not working for Argentina (Region: AR)

### ISSUE THREAD

**Issue by alphacentauri82** [nightscout/cgm-remote-monitor#6616]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**
MMCONNECT doesn't support AR (Argentina). Can't use the US region for login.

**To Reproduce**
1. Use an account from non EU nor US to login 

**Expected behavior**
No data shows.

**Your setup information**
- What version of Nightscout : latest
- What type of CGM, and how do you get your data there?: Carelink (670g/Guardian)

**Comment by benceszasz** [comment]
@alphacentauri82 what is the url of the CareLink Connect web app in Argetina? You can see it in your browser after you open the Connect web app in CareLink (for example it is "https://carelink.minimed.**eu**/app/connect" in the EU, "https://carelink.minimed.**com**/app/connect" in the US).

**Comment by jhuang234** [comment]
We met same issue in the EU: https://carelink.minimed.eu/app/connect
Error message:
2020-12-07T01:13:23.756746+00:00 app[web.1]: tick 2020-12-07T01:13:23.756Z
2020-12-07T01:13:28.973020+00:00 app[web.1]: Load Complete:
2020-12-07T01:13:28.973052+00:00 app[web.1]: 	 sgvs:20, profiles:1, devicestatus:13
2020-12-07T01:13:28.975244+00:00 app[web.1]: data loaded: reloading sandbox data and updating plugins
2020-12-07T01:13:31.641132+00:00 app[web.1]: MiniMed Connect error: Error: connect ETIMEDOUT 144.15.107.20:443
2020-12-07T01:13:31.641170+00:00 app[web.1]: stack: Error: connect ETIMEDOUT 144.15.107.20:443
2020-12-07T01:13:31.641171+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
[app-logs-1607303629124.txt](https://github.com/nightscout/cgm-remote-monitor/files/5650168/app-logs-1607303629124.txt)

**Comment by giannicuccu** [comment]
Same issue here, using Nightscout 14.0.7 on Heroku, connecting to carelink EU portal.
Error log:
MiniMed Connect error: Error: connect ETIMEDOUT 144.15.107.20:443
Dec 07 00:00:28 appurl app/web.1 stack: Error: connect ETIMEDOUT 144.15.107.20:443
Dec 07 00:00:28 appurl app/web.1     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)

**Comment by jhuang234** [comment]
Hi all, please try to redeploy nightscout (from the same got repo) in the US heroku, see raferg's comment:
https://github.com/nightscout/minimed-connect-to-nightscout/issues/12#issuecomment-739737066

**Comment by giannicuccu** [comment]
Redeployng in the US Heroku solved the issue for me, 
hope US servers will not blacklisted.

**Comment by alphacentauri82** [comment]
I'm in the US trying to set up nightscout for my 7 year old niece in
Argentina. The URL for carelink is localised I suppose

**Comment by benceszasz** [comment]
**These seems to be very different issues!**
**1. CareLink in Argetina not working** 
Only US and EU CareLink servers are handled by the current version of mmconnect. Argetina is in a different region, I think that they have a different CareLink Connect provider server, hopefully alphacentauri82 will confirm it and provide the correct address.

**2.  CareLink in US is not working**
It seems that CareLink in the US now also uses the same new central login process as the EU, but because the login process was only changed for EU thus US is not working at all. If this is true, then the new login process should be used in case of US too with US region and language parameters.

**3. EU - repeated random stops since 07.2020**
There was a bug in the new EU version (since 07.2020), which stopped mmconnect after the first temporary error from CareLink EU server, which can happen in every few hours or days. After restart of the cgm-remote-monitor mmconnect starts to work until the next temporary CareLink server error.

**4. EU - not working since 06.12.2020**
It seems, that CareLink EU blocks all requests from Heroku Europe. This issue can be solved by deploying the cgm-remote-monitor in Heroku US, but it is possibe, that sooner or later Medtronic will also block Herokus US IPs. Possible long term solution could be a mobile application (for example a new nigthscout uploader application for CareLink or CareLink Connect plugin for xDrip+), which collects the data from CareLink and uploads to cgm-remote-monitor.

**Comment by FredMK** [comment]
@benceszasz I can confirm error 3 and 4. 
Error 3 was my fault, fixed it in my repo: [https://github.com/FredMK/cgm-remote-monitor/tree/axios2](https://github.com/FredMK/cgm-remote-monitor/tree/axios2)

Error 4 is sadly seems true. With the above repo the connection time to Carelink is maximized to 5 minutes, no retry within this period.

**Comment by raferg** [comment]
So if I run this on my own server - Error 4 will not be a problem until they blacklist me?

**Comment by benceszasz** [comment]
Yes, I can run the mmconnect as a node js app on my computer without any problem. Medtronic cannot blacklist all IP and they can't see whether you are using a custom program to retrieve the data or you are using a browser.

**Comment by raferg** [comment]
looks like medtronic just started blocking heroku US as well 

sadness

**Comment by FredMK** [comment]
For me it's still working. What is the error message in the log for Carelink connect?

**Comment by raferg** [comment]
The message was the same as last time, so i cloned 'minimed-connect-to-nightscout' locally, and set it up to upload from my desktop. 

Just switched over to the old method (re-enabled mmconnect on heroku) ... and now it is working again, I wouldn't be surprised if this goes again in the next few days.

**Comment by alphacentauri82** [comment]
So, found out that argentina uses the EU URL, but my heroku US account is
blocked. Such a pain. May I ask to those who run it separately and upload
to nightscout, how do they do it?

**Comment by raferg** [comment]
I'm running Ubuntu, and the instructions were on the
'minimed-connect-to-nightscout' github page. The most complex part of the
instructions is setting the variables (don't forget to export them rather
than just set). Other than that it literally should just work.

Once you have that up, remove the mmconnect from the modules on your
heroku. All you are doing is replacing one plugin, it the entire system.

**Comment by dacia1300** [comment]
**> **4. EU - not working since 06.12.2020****
> It seems, that CareLink EU blocks all requests from Heroku Europe. This issue can be solved by deploying the cgm-remote-monitor in Heroku US

I created a new Heroku account with the Us region set and deployed the cgm-remote-monitor. 
It worked for almost 24h without issues. It stopped working about an hour ago. 
MiniMed Connect error: Error: connect ETIMEDOUT 144.15.107.20:443  appears in the logs.


![1](https://user-images.githubusercontent.com/67636834/101518225-4f155400-398a-11eb-9b8f-333258c8de0f.jpg)

**Comment by raferg** [comment]
@FredMK How big a leap is it to get the medtronic minimed code into xdrip+?

**Comment by FredMK** [comment]
@raferg It is possible, but currently I don't have time to do it. I have limited experience in Android development, for me it takes at least one week.
My problem with this, that this would not be the solution for the Apple users of the community.

I think we should contact Medtronic and ask them what is the problem, maybe we can get an answer and find a solution, we are paying customers after all. If we can find a solution, maybe they lift the ban from Heroku. I checked the code, and currently the request count is 5x more than it would be necessary. I can optimize the server load for Carelink made by mmconnect and do 80% less requests with the same result. Currently mmconnect makes a request every 1 minute, when the data is only uploaded to Carelink every 5 minutes. The exact time when the next upload is expected can be calculated from the last successful request.

**Comment by raferg** [comment]
@FredMK 
I understand the issue with the lack of time and experience - and the issue with keeping the solution workable for both Android and Apple. 

As soon as you mentioned contacting Medtronic I could feel my jaw clench and the desire to drop rocks on my feet increasing. I think it is the logical step, but then I recall every service call I've done so far and the experience makes me doubt the sanity of that action! I'm also not a paying customer at the moment - currently have over 4 months of sensors left from my last subscription (which should take me another 8 months to consume). 

**or** 
Would it be more worthwhile going through my local rep than it would be to go through the service centre?

**Comment by raferg** [comment]
Seeing the comments elsewhere I think the rep will be the best option. Other people have contacted support with no help forthcoming.

**Comment by bewest** [comment]
What is the URL currently used to log in with a browser to Medtronic Carelink?

We have patches available for testing purposes here: https://github.com/nightscout/minimed-connect-to-nightscout/pull/17, https://github.com/nightscout/cgm-remote-monitor/pull/6657

**Comment by dacia1300** [comment]
The first link is for chosing a country and language. (I chose Romania and english)
https://carelink.minimed.eu/app/login
This next link is the next screen where you have to add your username and password.

https://mdtlogin.medtronic.com/mmcl/auth/oauth/v2/authorize/login?action=display&sessionID=89a704c7-0bba-4d91-b7bc-15816f3c79ad&sessionData=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ew0KICAgICJzZXNzaW9uIjogew0KICAgICAgICAic2Vzc2lvbklEIjoiODlhNzA0YzctMGJiYS00ZDkxLWI3YmMtMTU4MTZmM2M3OWFkIiwNCiAgICAgICAgImV4cCI6MTYwODU0MzIwMiwNCiAgICAgICAgImN1cnJlbnRfdXNlcm5hbWUiOiIiLA0KICAgICAgICAiY3VycmVudF91c2VyX2NvbnNlbnQiOiJub25lIiwNCiAgICAgICAgImN1cnJlbnRfdXNlcl9yb2xlIjoiIiwNCiAgICAgICAgImN1cnJlbnRfdXNlcl9hY3IiOiIwIiwNCiAgICAgICAgImN1cnJlbnRfdXNlcl9hdXRoVGltZSI6IjAiLA0KICAgICAgICAiY3VycmVudF91c2VyX2F0dHJpYnV0ZXMiOiIiLA0KICAgICAgICAic2FsdCI6IiIsDQogICAgICAgICJ0aGlyZF9wYXJ0eV9zc29fdG9rZW4iOiIiLA0KICAgICAgICAidGhpcmRfcGFydHlfc3NvX3Rva2VuX3R5cGUiOiIiDQogICAgfSwNCiAgICAicmVxdWVzdF9jb25zZW50Ijogew0KICAgICAgICAiY2xpZW50X25hbWUiOiJPQ0wrd2ViK2FwcCIsDQogICAgICAgICJzY29wZV92ZXJpZmllZCI6Im9wZW5pZCtwcm9maWxlK3JvbGVzIg0KICAgIH0sDQogICAgInJlcXVlc3RfcGFyYW1ldGVycyI6IHsNCiAgICAgICAgImRpc3BsYXkiOiJwYWdlIiwNCiAgICAgICAgInByb21wdCI6ImxvZ2luK2NvbnNlbnQiLA0KICAgICAgICAiaWRfdG9rZW5faGludCI6IiIsDQogICAgICAgICJsb2dpbl9oaW50IjoiIiwNCiAgICAgICAgImFjcl92YWx1ZXMiOiIiLA0KICAgICAgICAiY2xpZW50X2lkIjoiYjMzMGZhMTEtMGZjMS00Mjg0LTgwMGUtZDUxYTRhNWE1YTBlIiwNCiAgICAgICAgIm5vbmNlIjoiIiwNCiAgICAgICAgInNjb3BlIjoib3BlbmlkK3Byb2ZpbGUrcm9sZXMiLA0KICAgICAgICAibWF4X2FnZSI6ICIiDQogICAgfQ0KfQ.xVan-KXxmZj5D3l14rQxHK65DwiIJyMBXNNa8CNzEys&locale=en&countrycode=ro
![1](https://user-images.githubusercontent.com/67636834/102756592-d0042080-4378-11eb-9cac-5c6baee59919.jpg)

**Comment by Grynn** [comment]
Heroku EU / US both are not working for me. Region: IN (India)

Quick check:
`heroku run "curl -sL  'https://carelink.minimed.eu/patient/sso/login?country=gb&lang=en'"` returns access denied

but if I run the same command locally:
curl -sL  'https://carelink.minimed.eu/patient/sso/login?country=gb&lang=en' - it works fine.

So Medtronic is blocking some range of AWS addresses :(

**Comment by artempartos** [comment]
See the same problem - looks like Medtronic blocking AWS IP ranges

**Comment by AndyLow91** [comment]
Closing this as the mmconnect plugin has since ben deprecated due to major breaking changes from Medtronic
