### ISSUE TITLE
Error at startup because the roles of MongoDB are undefined in mongo-storage.js

### ISSUE THREAD

**Issue by snics** [nightscout/cgm-remote-monitor#6803]
@pazaan, I have an error with the following line of code. Therefore would suggest to adjust the code so far:
```JavaScript
 if (roles && roles.length > 0 && roles[0].role == 'readAnyDatabase')
```
Otherwise this always leads to the following error:
```
ERROR CONNECTING TO MONGO Error: MONGODB_URI mongodb://*****:*****@nightscoutdb/admin seems invalid: Cannot read property 'length' of undefined
at connect_with_retry (/opt/app/lib/storage/mongo-storage.js:72:16)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
What do you think of it? I would also create a pull request but wanted to ask me first why the code looks like that? It may be that I have set something wrong in MongoDB.

**Comment by sulkaharo** [comment]
Do you have authentication enabled in Mongo?

**Comment by sulkaharo** [comment]
@snics please comment - can't repro and thus can't fix. Which MongoDB version are you running?

**Comment by snics** [comment]
Sorry @sulkaharo I get in touch in the course of the day am unfortunately not yet come to it 😅.

**Comment by DN0000** [comment]
Hi @snics - I'd be keen to hear if you managed to get to the bottom of this one? Trying to self-host on Docker Swarm and hitting the same message and the only search results keep leading me back here :)

Running against both nightscout/cgm-remote-monitor:latest_dev and nightscout/cgm-remote-monitor:latest produces same result.

Seeing the below in the Nightscout output:
`Successfully established connection to MongoDB`
`ERROR CONNECTING TO MONGO Error: MONGODB_URI seems invalid: Cannot read property 'length' of undefined`
`    at connect_with_retry (/opt/app/lib/storage/mongo-storage.js:69:16)`
`    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
`ngo Storage system ready`



And from the DB, which does have authentication enabled:
`2021-02-22T21:36:06.003+0000 [initandlisten] waiting for connections on port 27017`
`2021-02-22T21:36:06.003+0000 [websvr] admin web console waiting for connections on port 28017`
`2021-02-22T21:36:24.864+0000 [initandlisten] connection accepted from 10.0.16.4:47016 #1 (1 connection now open)`
`2021-02-22T21:36:24.883+0000 [initandlisten] connection accepted from 10.0.16.4:47018 #2 (2 connections now open)`
`2021-02-22T21:36:24.889+0000 [conn2]  authenticate db: admin { authenticate: 1, user: "admin", nonce: "xxx", key: "xxx" }`
`2021-02-22T21:37:05.814+0000 [clientcursormon] mem (MB) res:53 virt:102877`

MongoDB Version:
`root@61038ae607ec:/# mongo`
`MongoDB shell version: 2.6.11`
`connecting to: test`
`Welcome to the MongoDB shell.`
`For interactive help, type "help".`
`For more comprehensive documentation, see`
`        http://docs.mongodb.org/`
`Questions? Try the support group`
`        http://groups.google.com/group/mongodb-user`
`> version()`
`2.6.11`
`> `

 I'm assuming it's user error on the DB permissions, but I'm not well versed at all with Mongo.

**Comment by pazaan** [comment]
What's your mongo setup? Are you using AtlasDB? Or a self-hosted MongoDB?

**Comment by DN0000** [comment]
Self hosted, using the offical docker "mongo:4.4" image.

Is there a more appropriate forum to work this problem? I appreciate this is most likely a config not a code problem and dont want to be clogging up the issues.

**Comment by sulkaharo** [comment]
Data point: one user who had this error did fix it by migrating from a 5 year old Mongo Docker image to the 4.4 image

**Comment by juehv** [comment]
I have the same issue while using the docker images :(

**Comment by AndyLow91** [comment]
Closing this as resolved.

The startup crash described here was caused by checking `roles.length` when MongoDB returned no `authenticatedUserRoles` array. Current `dev` guards that check before reading `.length`, so an undefined roles value no longer causes this startup failure.

If this reappears on current `dev`, please comment with the MongoDB version, connection string shape, and the startup log.
