### ISSUE TITLE
Mongo Uri connection error

### ISSUE THREAD

**Issue by Dave2526** [nightscout/cgm-remote-monitor#6918]
Hi, 
I set up nightscout 14.2.2 on docker on my raspberry pi. One container for nightscout and an other container with Mongodb. With v 14.0.6 all works fine. But now it won't connect to the Mongo DB. My setup was the env MONGO_CONNECTION=mongodb://172.17.0.8/nightscout, I made MONGODB_URI=mongodb://172.17.0.8/nightscout, but now it always shows the following error:

Successfully established connection to MongoDB

ERROR CONNECTING TO MONGO Error: MONGODB_URI seems invalid: Cannot read property 'length' of undefined
at connect_with_retry (/home/node/app/lib/storage/mongo-storage.js:69:16)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
Mongo Storage system ready

What could it be? In the docs I found Nothing about it, Thanks Dave2525

**Comment by Dave2526** [comment]
Ok I found it, my fault. On raspberry there only Mongodb v2.x, it won't work with it

**Comment by Dave2526** [comment]
Solved
