### ISSUE TITLE
Error 403 Minimed Connect

### ISSUE THREAD

**Issue by ZachieBlade** [nightscout/cgm-remote-monitor#7093]
Hello,

Getting this error with MMConnect.

2021-08-23T16:48:14.433804+00:00 app[web.1]: MiniMed Connect error: Error: Request failed with status code 403
2021-08-23T16:48:14.433813+00:00 app[web.1]: stack: Error: Request failed with status code 403
2021-08-23T16:48:14.433814+00:00 app[web.1]:     at createError (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
2021-08-23T16:48:14.433815+00:00 app[web.1]:     at settle (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
2021-08-23T16:48:14.433816+00:00 app[web.1]:     at /app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
2021-08-23T16:48:14.433816+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-08-23T16:48:14.433817+00:00 app[web.1]:     at responseInterceptor (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
2021-08-23T16:48:14.433817+00:00 app[web.1]:     at /app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67
2021-08-23T16:48:14.433817+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-08-23T16:48:14.433818+00:00 app[web.1]:     at async doLoginEu1 (/app/node_modules/minimed-connect-to-nightscout/carelink.js:147:16)
2021-08-23T16:48:14.433818+00:00 app[web.1]:     at async checkLogin (/app/node_modules/minimed-connect-to-nightscout/carelink.js:248:32)
2021-08-23T16:48:14.433818+00:00 app[web.1]:     at async Object.fetch (/app/node_modules/minimed-connect-to-nightscout/carelink.js:279:21)

Seen this for a while, I thought it was fixed tho. :|

**Comment by psonnera** [comment]
Yes. Carelink blocks Heroku. Nothing to do. Try xDrip+ https://nightscout.github.io/uploader/uploaders/#medtronic

**Comment by AndyLow91** [comment]
Closing this as the mmconnect plugin has since ben deprecated due to major breaking changes from Medtronic
