### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by EleonoraMingione** [nightscout/cgm-remote-monitor#7104]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**
Recently the app doesn't show any data and started to log;
```
2021-09-17T19:55:50.881094+00:00 heroku[router]: at=info method=POST path="/api/v1/entries" host=glycemi.herokuapp.com request_id=4a2f55aa-24db-4bc2-8c41-a0a3016f6e59 fwd="212.216.126.230" dyno=web.1 connect=0ms service=10ms status=413 bytes=1226 protocol=https
2021-09-17T19:55:50.880974+00:00 app[web.1]: PayloadTooLargeError: request entity too large
2021-09-17T19:55:50.880982+00:00 app[web.1]:     at readStream (/app/node_modules/raw-body/index.js:155:17)
2021-09-17T19:55:50.880982+00:00 app[web.1]:     at getRawBody (/app/node_modules/raw-body/index.js:108:12)
2021-09-17T19:55:50.880982+00:00 app[web.1]:     at read (/app/node_modules/body-parser/lib/read.js:77:3)
2021-09-17T19:55:50.880983+00:00 app[web.1]:     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
2021-09-17T19:55:50.880984+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-09-17T19:55:50.880984+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2021-09-17T19:55:50.880984+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2021-09-17T19:55:50.880984+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2021-09-17T19:55:50.880985+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2021-09-17T19:55:50.880985+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
```

**Expected behavior**
My data visible on the cloud app.

**Your setup information**
- Nightscout ver 14.2.2 on Heroku and MongoDB 4.8.8
- What type of CGM, and how do you get your data there? Libre 2, Diabox 1.0 (9.0.6)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? Any device/browser, the errore in on the server.

**Additional context**
I tried to check on the files inside the deploy but can't file any configuration for lenght limit. Gotta know if I have to configure something or is a global value to adjust.
From the log all the POST give the error above but all GET are receiving 200, so the web server is working.

tyvm

**Comment by old-square-eyes** [comment]
I think I have this issue too. I am able to resolve it by dropping my treatments collection. But it comes back a couple of days later.

I'm using OpenAPS, which makes POST requests. Symptom is OpenAPS balas rates and bolus treatments are not displayed on NS.

I see `<h2><em>413</em> PayloadTooLargeError: request entity too large</h2>` in my OpenAPS logs.

This happens on Master and Dev NS for me.

**Comment by old-square-eyes** [comment]
![image](https://user-images.githubusercontent.com/25760491/134830610-ec03e7e0-7128-4f12-a3c3-e7fabc6654f8.png)

Here is my NS breaking only an hour after I dropped the Treatments Collection.

**Comment by sulkaharo** [comment]
Your Mongo getting up to 4 treatment updates / second doesn't sound right at all and must be caused by a client you have accessing the database. Do you have any other software connected to the site other than OpenAPS that might be modifying the data?

**Comment by old-square-eyes** [comment]
@sulkaharo xDrip, which does the occasional carb entry, Two OpenAPS rigs looping. And NSClient for careportal/carb entry. But I've had this setup for a couple of years.

**Comment by old-square-eyes** [comment]
I checked my Pihole DNS logs and each OpenAPS rig connects around 12 times a minute. My mobile - mostly NSClient I'm guessing, also ~12 times a minute.

**Comment by old-square-eyes** [comment]
To me though, the request size warning is unusual.

**Comment by EleonoraMingione** [comment]
Actually I replaced Diabox with xdrip and since 5 days everything is working fine.
Probably the error inside Diabox.

Closing this.

**Comment by checkatillo** [comment]
I've recently seen the same in someone else's xdrip+ on Android.

**Comment by old-square-eyes** [comment]
@sulkaharo this is now closed... do I need to open a new issue?

**Comment by old-square-eyes** [comment]
Still having to drop my treatments collection every day.
