### ISSUE TITLE
Pushover acknowledge receipt doesn't work

### ISSUE THREAD

**Issue by yodax** [nightscout/cgm-remote-monitor#7170]
**Describe the bug**
When a pushover critical notification is acknowledged the alarm isn't suspended. An error appears in the log. 

**To Reproduce**
1. Acknowledge a critical notification
2. Check logs

**Expected behavior**
The alarm should be suspended. 

**Screenshots**
```
TypeError: Cannot read property 'receipt' of undefined
    at Function.pushoverAck (/usr/home/nightscout/cgm-remote-monitor/lib/server/pushnotify.js:59:19)
    at /usr/home/nightscout/cgm-remote-monitor/lib/api/notifications-api.js:11:24
    at Layer.handle [as handle_request] (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/layer.js:95:5)
    at /usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/home/nightscout/cgm-remote-monitor/node_modules/express/lib/router/index.js:174:3)

```

**Your setup information**
- What version of Nightscout 14.2.4
- Pushover on iOS.
- Nightscout is behind a HAProxy TLS offloading proxy. Nightscout is running on FreeBSD (13.0-RELEASE) with Node 14
- pm2 env: node_version: 14.18.1 version: 14.2.4
- This worked with the previous release of nightscout on Node 12. (Node 12 was removed from the FreeBSD package due to security issues)

**Comment by Rtzftz** [comment]
Still the same with Nightscout 14.2.6 on Debian 10.13, node 16.8.1

**Comment by yodax** [comment]
Fixed by: https://github.com/nightscout/cgm-remote-monitor/pull/7876
