### ISSUE TITLE
Remote Overrides fail - APNs delivery failed - Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#7310]
### **Describe the bug**
Using CarePortal event of Temporary Override, I attempt to submit the event. The care portal slide out does not go away. After 10 seconds to 1 minutes, a dialog box appears showing an error.

Heroku logs included below.

### **To Reproduce**
1. Click on  '+'
2. 'Select "Temporary Override"
3. Submit
4. See error on screen. Heroku log error shows up immediately.

### **Expected behavior**
Care Portal event screen goes away, override is received on the Looping phone and then reflected in NS.

### **Screenshots**
![image](https://user-images.githubusercontent.com/46848705/151105349-ef4179b6-98e5-403d-bf13-aa58f5ecd9bb.png)

![image](https://user-images.githubusercontent.com/46848705/151104986-25c76c05-3193-4da1-b98a-1ac5c6bd61b1.png)

### **Your setup information**
- What version of Nightscout: 14.2.5
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No. Browser used is Chrome on windows and chrome on Android 12. Others have confirmed on multiple Mac devices.

### **Additional context**
_**This issue affects all care givers of loopers using the remote overrides feature.**_ 

**Text from screenshot:**
I get this in the logs:
2022-01-26T03:18:52.382662+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-01-26T03:19:00.218880+00:00 app[web.1]: APNs delivery failed: [
2022-01-26T03:19:00.218890+00:00 app[web.1]: {
2022-01-26T03:19:00.218891+00:00 app[web.1]: device: 'c7c88d8f5347ecb5f86b646f1f29828aec153b89867e931c7acfcd49d3fea94e',
2022-01-26T03:19:00.218892+00:00 app[web.1]: error: VError: endpoint error: Client network socket disconnected before secure TLS connection was established
2022-01-26T03:19:00.218892+00:00 app[web.1]: at Endpoint.<anonymous> (/app/node_modules/apn/lib/protocol/endpointManager.js:69:32)
2022-01-26T03:19:00.218893+00:00 app[web.1]: at Endpoint.emit (events.js:314:20)
2022-01-26T03:19:00.218893+00:00 app[web.1]: at Endpoint.error [as _error] (/app/node_modules/apn/lib/protocol/endpoint.js:149:10)
2022-01-26T03:19:00.218894+00:00 app[web.1]: at TLSSocket.emit (events.js:326:22)
2022-01-26T03:19:00.218894+00:00 app[web.1]: at emitErrorNT (internal/streams/destroy.js:92:8)
2022-01-26T03:19:00.218894+00:00 app[web.1]: at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2022-01-26T03:19:00.218895+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2022-01-26T03:19:00.218895+00:00 app[web.1]: jse_shortmsg: 'endpoint error',
2022-01-26T03:19:00.218896+00:00 app[web.1]: jse_cause: [Error],
2022-01-26T03:19:00.218896+00:00 app[web.1]: jse_info: {}
2022-01-26T03:19:00.218896+00:00 app[web.1]: }
2022-01-26T03:19:00.218897+00:00 app[web.1]: }
2022-01-26T03:19:00.218897+00:00 app[web.1]: ]
2022-01-26T03:19:00.219201+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reason' of undefined
2022-01-26T03:19:00.219202+00:00 app[web.1]: at /app/lib/server/loop.js:127:75
2022-01-26T03:19:00.219203+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-01-26T03:19:00.219275+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html...). (rejection id: 4)

**Comment by sulkaharo** [comment]
The error is thrown in the backend when Nightscout is trying to communicate with Apple's servers (so the client referred to here is the Nightscout server), so it's hard to tell what's gone wrong. If I had to guess, Apple's push notification servers had a temporary glitch? The clean way to handle this would be to better detect the error in the NS client and tell user to retry later - I don't think we at least should have message queue for this purpose, as a later application of the temporary override might be unwanted.

**Comment by jonfawcett** [comment]
Yes this looks like it was an apple issue with the dev push servers. 

https://developer.apple.com/forums/thread/699248

**Comment by Nightfoxy** [comment]
Great news, that is wasn't a NS issue! Thanks, all. Sorry for the panic. 
I checked the APN server status and it was "up", but it must have been something else or Apple didn't update that page.
