### ISSUE TITLE
Nightscout crashes when NSClient is updated 

### ISSUE THREAD

**Issue by justass** [nightscout/cgm-remote-monitor#7502]
When NSClient is updated from 2.8.2 to newer version (3.0.0 and later), Nightscout crashes every few minutes.

nightscout version 14.2.5

Logs from heroku:

> 2022-08-01T09:45:55.799804+00:00 app[web.1]: Got results null
2022-08-01T09:45:55.802676+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:106
2022-08-01T09:45:55.802677+00:00 app[web.1]:       throw err;
2022-08-01T09:45:55.802677+00:00 app[web.1]:       ^
2022-08-01T09:45:55.802678+00:00 app[web.1]: 
2022-08-01T09:45:55.802678+00:00 app[web.1]: TypeError: Cannot read property '_id' of null
2022-08-01T09:45:55.802678+00:00 app[web.1]:     at hasId (/app/lib/server/cache.js:47:41)
2022-08-01T09:45:55.802679+00:00 app[web.1]:     at arrayFilter (/app/node_modules/lodash/lodash.js:582:11)
2022-08-01T09:45:55.802680+00:00 app[web.1]:     at Function.filter (/app/node_modules/lodash/lodash.js:9199:14)
2022-08-01T09:45:55.802680+00:00 app[web.1]:     at filterForAge (/app/lib/server/cache.js:46:16)
2022-08-01T09:45:55.802680+00:00 app[web.1]:     at mergeCacheArrays (/app/lib/server/cache.js:37:23)
2022-08-01T09:45:55.802681+00:00 app[web.1]:     at Stream.dataChanged (/app/lib/server/cache.js:83:30)
2022-08-01T09:45:55.802681+00:00 app[web.1]:     at Stream.emit (events.js:314:20)
2022-08-01T09:45:55.802681+00:00 app[web.1]:     at /app/lib/server/websocket.js:223:29
2022-08-01T09:45:55.802682+00:00 app[web.1]:     at executeCallback (/app/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
2022-08-01T09:45:55.802682+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:102:55)
2022-08-01T09:45:55.942746+00:00 heroku[web.1]: Process exited with status 1
2022-08-01T09:45:55.811659+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=imOWR1ienjMiERN0AAAA" host=aug-cgm.herokuapp.com request_id=f703f5a1-c352-4437-a693-8a4fcf416c2e fwd="78.56.199.112" dyno=web.1 connect=0ms service=25728ms status=101 bytes=129 protocol=https
2022-08-01T09:45:55.990205+00:00 heroku[web.1]: State changed from up to crashed
2022-08-01T09:45:55.885737+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=05KkR1ICZ-lZ2rHyAAAD" host=aug-cgm.herokuapp.com request_id=b89a88b2-95b3-46b4-b214-9412a96ed097 fwd="78.56.199.112" dyno=web.1 connect=0ms service=7109ms status=101 bytes=129 protocol=https
2022-08-01T09:45:55.811730+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=PGrtWXf5rm2EpI86AAAB" host=aug-cgm.herokuapp.com request_id=29e20308-5a8c-4e57-998a-c7e59b27f947 fwd="78.56.199.112" dyno=web.1 connect=0ms service=25038ms status=101 bytes=129 protocol=https
2022-08-01T09:45:58.923851+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aug-cgm.herokuapp.com request_id=7a9b3da6-4f99-4b2a-b120-d63751693cad fwd="78.56.199.112" dyno= connect= service= status=503 bytes= protocol=https

**Comment by justass** [comment]
For some reasons NSClient was trying to upload a profile to Nightscout. The request doesn't have the "_id" attribute, this might be the reason why Nightscout crashes.

2022-08-01T09:45:55.789159+00:00 app[web.1]: got data-received event, requesting reload
2022-08-01T09:45:55.789608+00:00 app[web.1]: [32mWS: [0mdbAdd client ID:  PGrtWXf5rm2EpI86AAAB  data:  {
2022-08-01T09:45:55.789609+00:00 app[web.1]:   collection: 'profile',
2022-08-01T09:45:55.789609+00:00 app[web.1]:   data: {
2022-08-01T09:45:55.789610+00:00 app[web.1]:     defaultProfile: 'LocalProfile1',
2022-08-01T09:45:55.789610+00:00 app[web.1]:     startDate: '2022-08-01T09:14:33.5220000Z',
2022-08-01T09:45:55.789610+00:00 app[web.1]:     store: { LocalProfile1: [Object] }
2022-08-01T09:45:55.789610+00:00 app[web.1]:   }
2022-08-01T09:45:55.789611+00:00 app[web.1]: }

Issue solved by clearing all the NSClient app data, uninstalling and installing new version.
