### ISSUE TITLE
Error: Cannot find module generateCacheBuster.js

### ISSUE THREAD

**Issue by GoudekettingRM** [nightscout/cgm-remote-monitor#7537]
**Describe the bug**
I just did a merge with the latest branch (using the update tool to make sure I got something that works), but I get a build error: 
The error I get is the following:  `Error: Cannot find module '/tmp/build_c5cf3d91/bin/generateCacheBuster.js'`

The full build log:
```
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  ^10.15.2 || ^8.15.1
       engines.npm (package.json):   ^6.4.1
       
       Resolving node version ^10.15.2 || ^8.15.1...
       Downloading and installing node 10.24.1...
       Bootstrapping npm ^6.4.1 (replacing 6.14.12)...
       npm 6.14.17 installed
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules
       
       > fsevents@1.2.13 install /tmp/build_c5cf3d91/node_modules/watchpack-chokidar2/node_modules/fsevents
       > node install.js
       
       
       Skipping 'fsevents' build as platform linux is not supported
       
       > ejs@2.7.4 postinstall /tmp/build_c5cf3d91/node_modules/ejs
       > node ./postinstall.js
       
       
       > fsevents@1.2.13 install /tmp/build_c5cf3d91/node_modules/nodemon/node_modules/fsevents
       > node install.js
       
       
       Skipping 'fsevents' build as platform linux is not supported
       
       > nodemon@1.19.4 postinstall /tmp/build_c5cf3d91/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       
       > nightscout@14.0.6 postinstall /tmp/build_c5cf3d91
       > webpack --mode production --config webpack.config.js && npm run-script update-buster
       
       Browserslist: caniuse-lite is outdated. Please run:
       npx browserslist@latest --update-db
       [BABEL] Note: The code generator has deoptimised the styling of /tmp/build_c5cf3d91/lib/language.js as it exceeds the max of 500KB.
       Hash: df72736ce47f69793d3b
       Version: webpack 4.44.1
       Time: 60672ms
       Built at: 09/06/2022 6:42:49 AM
                         Asset      Size  Chunks                          Chunk Names
              js/bundle.app.js  2.21 MiB       0  [emitted]        [big]  app
          js/bundle.app.js.map  7.67 MiB       0  [emitted] [dev]         app
            js/bundle.clock.js   624 KiB       1  [emitted]        [big]  clock
        js/bundle.clock.js.map  1.92 MiB       1  [emitted] [dev]         clock
           js/bundle.report.js  2.31 MiB       2  [emitted]        [big]  report
       js/bundle.report.js.map  8.01 MiB       2  [emitted] [dev]         report
       Entrypoint app [big] = js/bundle.app.js js/bundle.app.js.map
       Entrypoint clock [big] = js/bundle.clock.js js/bundle.clock.js.map
       Entrypoint report [big] = js/bundle.report.js js/bundle.report.js.map
        [35] ./lib/units.js 360 bytes {0} {1} {2} [built]
        [60] ./node_modules/d3/index.js + 521 modules 544 KiB {0} {2} [built]
             |    522 modules
       [212] (webpack)/buildin/harmony-module.js 573 bytes {0} {2} [built]
       [213] ./bundle/bundle.source.js 845 bytes {0} {2} [built]
       [214] ./static/css/drawer.css 1.06 KiB {0} {2} [built]
       [217] ./static/css/dropdown.css 1.07 KiB {0} {2} [built]
       [219] ./static/css/sgv.css 1.05 KiB {0} {2} [built]
       [230] ./lib/client/index.js 41.1 KiB {0} {2} [built]
       [450] ./lib/admin_plugins/index.js 2.31 KiB {0} {2} [built]
       [457] multi ./bundle/bundle.source.js 28 bytes {0} [built]
       [458] multi ./bundle/bundle.clocks.source.js 28 bytes {1} [built]
       [459] ./bundle/bundle.clocks.source.js 178 bytes {1} [built]
       [460] ./lib/client/clock-client.js 6.4 KiB {1} [built]
       [461] multi ./bundle/bundle.reports.source.js 28 bytes {2} [built]
       [462] ./bundle/bundle.reports.source.js 319 bytes {2} [built]
           + 462 hidden modules
       
       WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
       This can impact web performance.
       Assets: 
         js/bundle.app.js (2.21 MiB)
         js/bundle.clock.js (624 KiB)
         js/bundle.report.js (2.31 MiB)
       
       WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
       Entrypoints:
         app (2.21 MiB)
             js/bundle.app.js
         clock (624 KiB)
             js/bundle.clock.js
         report (2.31 MiB)
             js/bundle.report.js
       
       
       WARNING in webpack performance recommendations: 
       You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
       For more info visit https://webpack.js.org/guides/code-splitting/
       
       > nightscout@14.0.6 update-buster /tmp/build_c5cf3d91
       > node bin/generateCacheBuster.js >tmp/cacheBusterToken
       
       internal/modules/cjs/loader.js:638
           throw err;
           ^
       
       Error: Cannot find module '/tmp/build_c5cf3d91/bin/generateCacheBuster.js'
           at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
           at Function.Module._load (internal/modules/cjs/loader.js:562:25)
           at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
           at startup (internal/bootstrap/node.js:283:19)
           at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! nightscout@14.0.6 update-buster: `node bin/generateCacheBuster.js >tmp/cacheBusterToken`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the nightscout@14.0.6 update-buster script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.YO6iY/_logs/2022-09-06T06_42_49_776Z-debug.log
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! nightscout@14.0.6 postinstall: `webpack --mode production --config webpack.config.js && npm run-script update-buster`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the nightscout@14.0.6 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.YO6iY/_logs/2022-09-06T06_42_49_813Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - A module may be missing from 'dependencies' in package.json
         https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Additional context**
I set the heroku stack to upgrade to use heroku-22 (was at 18 before), could that pose any issues? I expect not, but I've also just had the software running since I started it about 2 years back without any issues (or updates in between 🙈)

**Comment by sulkaharo** [comment]
By latest, do you mean latest main or dev branch?

**Comment by GoudekettingRM** [comment]
Master, the branch the update tool recommended (:

**Comment by sulkaharo** [comment]
Can you just simply try again? I just tried with master and it deploys fine on the 22 stack. If that doesn't work, I'd assume something went wrong with the merge and you should delete your Github branch and fork again to get a fresh Master branch.

**Comment by GoudekettingRM** [comment]
Will do tonight, thanks for the quick replies btw

**Comment by GoudekettingRM** [comment]
@sulkaharo Appears you should not try to do these things when you're overloaded with other work. It seems I had somehow connected a different repo to the heroku app....

**Comment by sulkaharo** [comment]
Oops! 😅 Great you got this resolved. ❤️
