### ISSUE TITLE
MiniMed Connect not working - Error: Request failed with status code 504.

### ISSUE THREAD

**Issue by pen96** [nightscout/cgm-remote-monitor#8078]
No connection to MiniMed portal (Medtronic Carelink) from Nightscout App.  
**Error: Request failed with status code 504.**

Running Versions: 
 - Nightscout: 14.2.6 
 - Mongo DB: 5

Running in docker container.

Nightscout App Log Output:

MiniMed Connect error: Error: Request failed with status code 504
stack: Error: Request failed with status code 504
    at createError (/opt/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /opt/app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/opt/app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async doLoginEu1 (/opt/app/node_modules/minimed-connect-to-nightscout/carelink.js:155:16)
    at async checkLogin (/opt/app/node_modules/minimed-connect-to-nightscout/carelink.js:278:32)
    at async Object.fetch (/opt/app/node_modules/minimed-connect-to-nightscout/carelink.js:309:21)

**Comment by psonnera** [comment]
Might be worth trying dev and the new plugin http://nightscout.github.io/nightscout/plugins-v15/

**Comment by bewest** [comment]
Does it work in the Medtronic app?  There are widespread reports that Medtronic Carelink has not been working for many users for the better part of the last week.

**Comment by pen96** [comment]
> Might be worth trying dev and the new plugin http://nightscout.github.io/nightscout/plugins-v15/

Will try that later. 


> Does it work in the Medtronic app? There are widespread reports that Medtronic Carelink has not been working for many users for the better part of the last week.

Medtronic App and the connection from Medtronic App to the Medtronic portal seems to work for me (uploads,login,...) .
