### ISSUE TITLE
[Bug] Nightscout crashes when setting up connect_source_libre for the first time. 

### ISSUE THREAD

**Issue by billyjbryant** [nightscout/cgm-remote-monitor#8209]
**Describe the bug**
When Nightscout is configured with `CONNECT_SOURCE=linkup`, the server crashes upon initial load of data from Libre Link Up. This is due to a bug in `nightscout_connect` which improperly handles data ingestion when there are no previous data points. 

If last_known is null, the plugin crashes with the following error, causing a reboot loop on the container:

```js
 /opt/app/node_modules/nightscout-connect/lib/sources/librelinkup.js:124
       var last_updated = last_known.entries;
                                     ^

 TypeError: Cannot read properties of null (reading 'entries')
     at Object.transformGlucose [as transformer] (/opt/app/node_modules/nightscout-connect/lib/sources/librelinkup.js:124:37)
     at transformService (/opt/app/node_modules/nightscout-connect/lib/machines/fetch.js:14:37)
     at Interpreter._exec (/opt/app/node_modules/xstate/lib/interpreter.js:269:63)
     at Interpreter.exec (/opt/app/node_modules/xstate/lib/interpreter.js:1026:10)
     at Interpreter.execute (/opt/app/node_modules/xstate/lib/interpreter.js:387:14)
     at Interpreter.update (/opt/app/node_modules/xstate/lib/interpreter.js:415:12)
     at /opt/app/node_modules/xstate/lib/interpreter.js:110:15
     at Scheduler.process (/opt/app/node_modules/xstate/lib/scheduler.js:69:7)
     at Scheduler.schedule (/opt/app/node_modules/xstate/lib/scheduler.js:48:10)
     at Interpreter.send (/opt/app/node_modules/xstate/lib/interpreter.js:104:23)
```

This issue is fixed in `nightscout_connect` by adding in appropriate checks to ensure that direct reference to an undefined var are not performed and thus prevents the plugin from crashing.

This does not fix the crash in Nightscout as a result of the plugin crashing. 

**To Reproduce**
1. Configure the environment variables for Libre Link Up as directed here: https://github.com/nightscout/cgm-remote-monitor?tab=readme-ov-file#libre-link-up
1. Start the Nightscout server
1. Monitor server logs
1. Upon retrieving data from Link Up the plugin crashes

**Expected behavior**
Connect should retrieve the patient data from LinkUp, process it then send it to Nightscout

**Screenshots**
N/A

**Your setup information**
- Nightscout 15.0.2
- Freestyle Libre 3 + Libre Link up

**Additional context**
This bug was originally posted in https://github.com/nightscout/nightscout-connect/issues/27, cross posting it here because the failure in the connect plugin causes Nightscout to crash and restart, which is indicative of an error handling issue. 
The connect issue is fixed in https://github.com/nightscout/nightscout-connect/pull/34

**Comment by AndyLow91** [comment]
Thanks for raising this.

I’ve reviewed the linked `nightscout-connect` fix. The underlying Libre LinkUp crash was addressed in nightscout/nightscout-connect#34, but I don’t think we should close this issue as resolved yet.

At the moment, the latest published `nightscout-connect` package is still `0.0.12`, and `cgm-remote-monitor` is still locked to that version. That means current Nightscout installs may not yet include the fix, even though the patch has been merged in the `nightscout-connect` repository.

I think the remaining work is:

1. publish a new `nightscout-connect` release containing nightscout/nightscout-connect#34
2. update `cgm-remote-monitor` to depend on that fixed version
3. confirm that first-time `CONNECT_SOURCE=linkup` setup no longer crashes Nightscout when there is no previous data

Once that dependency update is in Nightscout, this issue should be safe to close.

**Comment by AndyLow91** [comment]
The dependency update identified in the May review has now landed. `nightscout-connect` v0.0.13 includes nightscout/nightscout-connect#34, and Nightscout adopted that version through #8556 and #8557. Both PRs are present in `dev` and `master`, including release 15.0.8.

A focused regression check reproduced the `last_known === null` crash with v0.0.12. With v0.0.13, the transform retained the synthetic glucose readings and the alignment and mocked-fetch paths handled null, undefined and empty prior state. This verifies the reported first-run defect; the check did not use a live Libre account.

Closing as resolved. If this same failure occurs on 15.0.8 or newer, please provide the version and relevant logs so we can investigate.
