### ISSUE TITLE
CGM upload fails

### ISSUE THREAD

**Issue by janvv** [nightscout/cgm-remote-monitor#8322]
**Describe the bug**
When opening nightscout, there is no CGM data, only carbs. When checking the northflank logs, it appears that the CGM fails to upload because it is too large. 

**To Reproduce**
Open nightscout

**Expected behavior**
See all data, including CGM

**Screenshots**
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/9d860dc6-304f-4cfe-98bb-4934995060d7" />

```
2024-12-17T08:17:38.595851854Z stdout F Loop hasn't reported a loop yet
2024-12-17T08:17:38.514335484Z stdout F data loaded: reloading sandbox data and updating plugins
2024-12-17T08:17:38.514327068Z stdout F 	 treatments:11, profiles:1, sitechangeTreatments:1, sensorTreatments:1
2024-12-17T08:17:38.514286513Z stdout F Load Complete:
2024-12-17T08:17:33.39712351Z stdout F got data-received event, requesting reload
2024-12-17T08:17:32.393194206Z stdout F got data-received event, requesting reload
2024-12-17T08:17:31.275403079Z stdout F got data-received event, requesting reload
2024-12-17T08:17:30.911975268Z stderr F     at expressInit (/workspace/node_modules/express/lib/middleware/init.js:40:5)
2024-12-17T08:17:30.911962004Z stderr F     at next (/workspace/node_modules/express/lib/router/index.js:275:10)
2024-12-17T08:17:30.911955291Z stderr F     at Function.process_params (/workspace/node_modules/express/lib/router/index.js:335:12)
2024-12-17T08:17:30.911947487Z stderr F     at /workspace/node_modules/express/lib/router/index.js:284:7
2024-12-17T08:17:30.9119387Z stderr F     at trim_prefix (/workspace/node_modules/express/lib/router/index.js:317:13)
2024-12-17T08:17:30.911902443Z stderr F     at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
2024-12-17T08:17:30.911895359Z stderr F     at jsonParser (/workspace/node_modules/body-parser/lib/types/json.js:135:5)
2024-12-17T08:17:30.911888787Z stderr F     at read (/workspace/node_modules/body-parser/lib/read.js:77:3)
2024-12-17T08:17:30.911882726Z stderr F     at getRawBody (/workspace/node_modules/raw-body/index.js:108:12)
2024-12-17T08:17:30.911872607Z stderr F     at readStream (/workspace/node_modules/raw-body/index.js:155:17)
2024-12-17T08:17:30.911785565Z stderr F PayloadTooLargeError: **request entity too large**
...
```

**Your setup information**
- What version of Nightscout  14.2.3
- Loop iOS
- No

**Additional context**
Yes, Loop Nightscout service is active and other data is being uploaded (carbs, treatments).

I believe this is the cause:
I kept having crashes because of lost connection to northflank mongo database: https://github.com/nightscout/nightscout.github.io/issues/217 
Even though mongoDB Compass was able to connect to the mongo DB, restarting loop gave me the same error.
Therefore, today, i updated to the develop branch. Now, nightscout started but does not show cgm data. 
I believe Loop might have cached too much CGM that nightscout fails receiving it.

**Comment by janvv** [comment]
I found a workaround: I updated the upload size in the nightscout-service to 100 samples (instead of 1k). This seems to solve the problem. I now have CGM data.

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/9325d6da-78f1-4a76-9bfc-efd00410a95c" />


```bash
2024-12-17T09:27:31.902200239Z stdout F got data-received event, requesting reload
2024-12-17T09:27:31.797809358Z stdout F got data-received event, requesting reload
2024-12-17T09:27:30.902874609Z stdout F got data-received event, requesting reload
2024-12-17T09:27:30.094590105Z stdout F got data-received event, requesting reload
2024-12-17T09:27:29.205303755Z stdout F got data-received event, requesting reload
2024-12-17T09:27:28.507151939Z stdout F got data-received event, requesting reload
2024-12-17T09:27:27.999700127Z stdout F got data-received event, requesting reload
2024-12-17T09:27:27.498404775Z stdout F got data-received event, requesting reload
2024-12-17T09:27:26.891641898Z stdout F got data-received event, requesting reload
2024-12-17T09:27:25.994279171Z stdout F got data-received event, requesting reload
2024-12-17T09:27:25.304506795Z stdout F got data-received event, requesting reload
2024-12-17T09:27:24.78902456Z stdout F got data-received event, requesting reload
2024-12-17T09:27:23.901354647Z stdout F got data-received event, requesting reload
2024-12-17T09:27:23.309376981Z stdout F got data-received event, requesting reload
2024-12-17T09:27:22.80163509Z stdout F got data-received event, requesting reload
2024-12-17T09:27:22.204132341Z stdout F got data-received event, requesting reload
2024-12-17T09:27:21.595360276Z stdout F got data-received event, requesting reload
2024-12-17T09:27:20.999436776Z stdout F got data-received event, requesting reload
2024-12-17T09:27:20.604616189Z stdout F got data-received event, requesting reload
2024-12-17T09:27:20.096832546Z stdout F got data-received event, requesting reload
2024-12-17T09:27:19.598147451Z stdout F got data-received event, requesting reload
2024-12-17T09:27:18.093847348Z stdout F got data-received event, requesting reload
2024-12-17T09:27:17.900675777Z stdout F got data-received event, requesting reload
2024-12-17T09:27:16.906565904Z stdout F got data-received event, requesting reload
``` 

The payload size limit might need to be updated.

**Comment by AndyLow91** [comment]
Thanks for reporting this, and for confirming the workaround.

I’ve reviewed this again and I don’t think we have enough evidence that this is a general Nightscout issue. The Nightscout entries API already allows large JSON uploads, and this issue has been open since December 2024 without other similar reports from Northflank or other hosting platforms.

The workaround you found, reducing the Loop Nightscout upload batch size from 1000 samples to 100 samples, suggests this may have been caused by a request-size limit somewhere in the deployment path rather than by Nightscout’s entries API itself.

I’m going to close this for now as we haven’t been able to reproduce it as a general Nightscout bug.

If you are still seeing this on a current Nightscout release, please reopen or comment with:

- your current Nightscout version
- whether you are still hosted on Northflank
- your Loop Nightscout upload batch size
- whether `SECURE_CSP` is set in your environment variables
- the full HTTP response/status code returned to Loop
- any current Northflank logs around the failed upload

With that information we can review again and determine whether there is a Nightscout-side change needed.
